package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
public final class MasterRoutes{private static final Map<Integer,MasterRoute>ROUTES=createRoutes();
private MasterRoutes(){}public static MasterRoute find(int masterId){return ROUTES.get(masterId);
}public static String getName(int masterId){MasterRoute route=find(masterId);
if(route!=null){return route.getName();
}return masterId>0?"Master ID "+masterId:"Unknown";
}private static Map<Integer,MasterRoute>createRoutes(){Map<Integer,MasterRoute>routes=new LinkedHashMap<>();
put(routes,1,text(27),2931,3536,0,"games necklace");
put(routes,2,"Mazchna",3510,3509,0,text(28),"slayer ring");
put(routes,3,"Vannaka",3147,9913,0,text(29),text(30));
put(routes,4,"Chaeldar",2445,4431,0,text(28),"slayer ring");
put(routes,5,"Duradel",2869,2982,1,text(31),text(32));
put(routes,6,"Nieve / Steve",2432,3423,0,text(28),"slayer ring");
put(routes,7,"Krystilia",3108,3516,0,text(29),text(30));
put(routes,8,"Konar",1308,3786,0,text(33),text(34));
put(routes,9,"Spria",3085,3250,0,text(29),text(30));
put(routes,10,"Mortimer",2589,8614,0,text(28),"slayer ring");
return Collections.unmodifiableMap(routes);
}private static void put(Map<Integer,MasterRoute>routes,int id,String name,int x,int y,int plane,String...returnItemFamilies){routes.put(id,new MasterRoute(id,name,new WorldPoint(x,y,plane),returnItemFamilies));
}@Getter public static final class MasterRoute{private final int id;
private final String name;
private final WorldPoint destination;
private final List<String>returnItemFamilies;
private MasterRoute(int id,String name,WorldPoint destination,String...returnItemFamilies){this.id=id;
this.name=name;
this.destination=destination;
this.returnItemFamilies=Collections.unmodifiableList(Arrays.asList(returnItemFamilies==null?new String[0]:returnItemFamilies.clone()));
}public String getReturnDestination(String family){String key=family==null?"":family.trim().toLowerCase(Locale.ENGLISH);
if(id==5&&key.startsWith(text(31))){return "Slayer Master";
}if(id==5&&key.startsWith(text(32))){return "Gem Mine";
}if(id==8&&key.startsWith(text(35))){return text(36);
}if(id==10&&key.contains("slayer ring")){return text(37);
}return name;
}}}
