package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
import lombok.Getter;
@Getter public final class MethodRules{public static final int MAX_TASK_METHOD_LENGTH=220;
public enum DamageControl{STRATEGY_DEFINED,DIRECT_DAMAGE,PARTIAL_MITIGATION,PRAYER_PROTECTED,SAFESPOT,FREEZE_SAFESPOT,STEP_UNDER,BOSS_MECHANICS}public enum DosePolicy{FULLEST_OWNED}public enum LayoutProfile{STANDARD,PRAYER_TASK,BARRAGE,FREEZE_MAGIC,CANNON,BOSS,HYBRID_BOSS,WILDERNESS}public enum Spellbook{STRATEGY_DEFINED,NONE,STANDARD,ANCIENT,ARCEUUS,LUNAR}public enum UtilityRecommendation{NONE,OPTIONAL,RECOMMENDED}public enum InventoryGroup{TRAVEL,UTILITY,SWITCH,RUNES,BOOST,PROTECTION,RESTORE,FOOD,OTHER}@Getter public static final class RequiredItem{private final String displayName;
private final int quantity;
private final int slotCount;
private final InventoryGroup group;
private final boolean ownedOnly;
private final List<String>alternatives;
private RequiredItem(String displayName,int quantity,int slotCount,InventoryGroup group,boolean ownedOnly,String...alternatives){this.displayName=clean(displayName);
this.quantity=Math.max(1,quantity);
this.slotCount=Math.max(1,slotCount);
this.group=group==null?InventoryGroup.OTHER:group;
this.ownedOnly=ownedOnly;
List<String>values=new ArrayList<>();
if(alternatives!=null){for(String alternative:alternatives){String value=clean(alternative);
if(!value.isEmpty()){values.add(value);
}}}this.alternatives=Collections.unmodifiableList(values);
}}@Getter public static final class RuneRequirement{private final int itemId;
private final String name;
private final int minimumQuantity;
private RuneRequirement(int itemId,String name,int minimumQuantity){this.itemId=itemId;
this.name=clean(name);
this.minimumQuantity=Math.max(1,minimumQuantity);
}}private final String coverageKey;
private final String method;
private final String researchSource;
private final String reviewDate;
private final boolean reviewed;
private final TaskStrategy.CombatStyle style;
private final Spellbook spellbook;
private final String primarySpell;
private final UtilityRecommendation thrallRecommendation;
private final UtilityRecommendation deathChargeRecommendation;
private final boolean wardOfArceuus;
private final boolean requireBookOfDead;
private final boolean requireRunePouch;
private final boolean requireDivineRunePouch;
private final int minimumMagicLevel;
private final List<RuneRequirement>pouchRunes;
private final boolean cannonMethod;
private final int cannonballQuantity;
private final DamageControl control;
private final DosePolicy dosePolicy;
private final LayoutProfile layoutProfile;
private final String primaryRestoreFamily;
private final String fallbackRestoreFamily;
private final boolean allowRestoreFallback;
private final int restoreSlotsOverride;
private final int foodSlotsOverride;
private final String foodDisplayName;
private final List<String>foodAlternatives;
private final boolean fillRestore;
private final boolean fillFood;
private final boolean includeStyleBoost;
private final boolean includeRunePouchForMagic;
private final int inventoryTarget;
private final int loot;
private final List<RequiredItem>requiredItems;
private MethodRules(Builder builder){coverageKey=clean(builder.coverageKey);
method=clean(builder.method);
researchSource=clean(builder.researchSource);
reviewDate=clean(builder.reviewDate);
reviewed=builder.reviewed;
style=builder.style;
spellbook=builder.spellbook;
primarySpell=clean(builder.primarySpell);
thrallRecommendation=builder.thrallRecommendation;
deathChargeRecommendation=builder.deathChargeRecommendation;
wardOfArceuus=builder.wardOfArceuus;
requireBookOfDead=builder.requireBookOfDead;
requireRunePouch=builder.requireRunePouch;
requireDivineRunePouch=builder.requireDivineRunePouch;
minimumMagicLevel=Math.max(0,builder.minimumMagicLevel);
pouchRunes=Collections.unmodifiableList(new ArrayList<>(builder.pouchRunes));
cannonMethod=builder.cannonMethod;
cannonballQuantity=Math.max(0,builder.cannonballQuantity);
control=builder.control;
dosePolicy=builder.dosePolicy;
layoutProfile=builder.layoutProfile;
primaryRestoreFamily=clean(builder.primaryRestoreFamily);
fallbackRestoreFamily=clean(builder.fallbackRestoreFamily);
allowRestoreFallback=builder.allowRestoreFallback;
restoreSlotsOverride=builder.restoreSlotsOverride;
foodSlotsOverride=builder.foodSlotsOverride;
foodDisplayName=clean(builder.foodDisplayName);
foodAlternatives=Collections.unmodifiableList(new ArrayList<>(builder.foodAlternatives));
fillRestore=builder.fillRestore;
fillFood=builder.fillFood;
includeStyleBoost=builder.includeStyleBoost;
includeRunePouchForMagic=builder.includeRunePouchForMagic;
inventoryTarget=clamp(builder.inventoryTarget,0,28);
loot=clamp(builder.loot,0,28);
requiredItems=Collections.unmodifiableList(new ArrayList<>(builder.requiredItems));
}public static Builder builder(){return new Builder();
}public boolean usesThralls(){return thrallRecommendation==UtilityRecommendation.RECOMMENDED;
}public boolean usesDeathCharge(){return deathChargeRecommendation==UtilityRecommendation.RECOMMENDED;
}public boolean usesWardOfArceuus(){return wardOfArceuus;
}public boolean requiresBookOfDead(){return requireBookOfDead;
}public boolean requiresRunePouch(){return requireRunePouch;
}public boolean requiresDivineRunePouch(){return requireDivineRunePouch;
}public boolean usesCannon(){return cannonMethod;
}public boolean allowsRestoreFallback(){return allowRestoreFallback;
}public boolean hasRestorePolicy(){return!primaryRestoreFamily.isEmpty();
}public boolean fillsRemainingWithRestore(){return fillRestore;
}public boolean fillsRemainingWithFood(){return fillFood;
}public boolean includesStyleBoost(){return includeStyleBoost;
}public boolean includesRunePouchForMagic(){return includeRunePouchForMagic;
}public boolean preventsExpectedDamageWhenExecuted(){return control==DamageControl.PRAYER_PROTECTED||control==DamageControl.SAFESPOT||control==DamageControl.FREEZE_SAFESPOT;
}public int resolveRestoreSlots(TaskStrategy strategy){if(restoreSlotsOverride>=0){return restoreSlotsOverride;
}return strategy==null?0:Math.max(0,strategy.getPrayers());
}public int resolveFoodSlots(TaskStrategy strategy,int strategyFoodSlots){if(foodSlotsOverride>=0){return foodSlotsOverride;
}if(preventsExpectedDamageWhenExecuted()){return 0;
}return Math.max(0,strategyFoodSlots);
}public void validateFor(String encounter,TaskStrategy strategy){String label=clean(encounter).isEmpty()?"Unknown Slayer encounter":clean(encounter);
if(!reviewed){throw new IllegalStateException(text(38)+label);
}if(coverageKey.isEmpty()){throw new IllegalStateException(text(39)+label);
}if(style==null){throw new IllegalStateException(text(40)+label);
}if(method.isEmpty()){throw new IllegalStateException(text(41)+label);
}if(method.length()>MAX_TASK_METHOD_LENGTH){throw new IllegalStateException(text(42)+label+": "+method.length()+" characters");
}if(researchSource.isEmpty()){throw new IllegalStateException(text(43)+label);
}if(reviewDate.isEmpty()){throw new IllegalStateException(text(44)+label);
}if(fillFood&&fillRestore){throw new IllegalStateException(text(45)+label);
}if(spellbook==Spellbook.ANCIENT&&primarySpell.isEmpty()){throw new IllegalStateException(text(46)+label);
}if(!pouchRunes.isEmpty()&&(spellbook==Spellbook.STRATEGY_DEFINED||spellbook==Spellbook.NONE)){throw new IllegalStateException(text(47)+label);
}if((usesThralls()||usesDeathCharge()||usesWardOfArceuus())&&spellbook!=Spellbook.ARCEUUS){throw new IllegalStateException(text(48)+label);
}if(usesThralls()&&!requireBookOfDead){throw new IllegalStateException(text(49)+label);
}if((usesThralls()||usesDeathCharge()||usesWardOfArceuus())&&!requireRunePouch){throw new IllegalStateException(text(50)+label);
}if(usesThralls()&&minimumMagicLevel<76){throw new IllegalStateException(text(51)+label);
}if(usesDeathCharge()&&minimumMagicLevel<80){throw new IllegalStateException(text(52)+label);
}if(usesWardOfArceuus()&&(spellbook!=Spellbook.ARCEUUS||minimumMagicLevel<73)){throw new IllegalStateException(text(53)+label);
}if((usesThralls()||usesDeathCharge()||usesWardOfArceuus())&&pouchRunes.isEmpty()){throw new IllegalStateException(text(54)+label);
}if(cannonMethod&&cannonballQuantity<=0){throw new IllegalStateException(text(55)+label);
}if((resolveRestoreSlots(strategy)>0||fillRestore)&&primaryRestoreFamily.isEmpty()){throw new IllegalStateException(text(56)+label);
}if(allowRestoreFallback&&fallbackRestoreFamily.isEmpty()){throw new IllegalStateException(text(57)+label);
}if((resolveFoodSlots(strategy,strategy==null?0:strategy.getFood())>0||fillFood)&&(foodDisplayName.isEmpty()||foodAlternatives.isEmpty())){throw new IllegalStateException(text(58)+label);
}int requiredSlotCount=0;
for(RequiredItem require:requiredItems){if(require.getDisplayName().isEmpty()){throw new IllegalStateException(text(59)+label);
}if(require.getAlternatives().isEmpty()){throw new IllegalStateException(text(60)+label+" -> "+require.getDisplayName());
}requiredSlotCount+=require.getSlotCount();
}if(requiredSlotCount>28){throw new IllegalStateException(text(61)+label+" -> "+requiredSlotCount+" slots");
}}private static String clean(String value){return value==null?"":value.trim();
}private static int clamp(int value,int minimum,int maximum){return Math.max(minimum,Math.min(maximum,value));
}public static final class Builder{private String coverageKey;
private String method;
private String researchSource;
private String reviewDate;
private boolean reviewed;
private TaskStrategy.CombatStyle style;
private Spellbook spellbook=Spellbook.STRATEGY_DEFINED;
private String primarySpell;
private UtilityRecommendation thrallRecommendation=UtilityRecommendation.NONE;
private UtilityRecommendation deathChargeRecommendation=UtilityRecommendation.NONE;
private boolean wardOfArceuus;
private boolean requireBookOfDead;
private boolean requireRunePouch;
private boolean requireDivineRunePouch;
private int minimumMagicLevel;
private final List<RuneRequirement>pouchRunes=new ArrayList<>();
private boolean cannonMethod;
private int cannonballQuantity;
private DamageControl control=DamageControl.STRATEGY_DEFINED;
private DosePolicy dosePolicy=DosePolicy.FULLEST_OWNED;
private LayoutProfile layoutProfile=LayoutProfile.STANDARD;
private String primaryRestoreFamily;
private String fallbackRestoreFamily;
private boolean allowRestoreFallback;
private int restoreSlotsOverride=-1;
private int foodSlotsOverride=-1;
private String foodDisplayName=text(62);
private final List<String>foodAlternatives=new ArrayList<>(Arrays.asList("anglerfish","manta ray","dark crab",text(63),"shark","sea turtle",text(64),"monkfish"));
private boolean fillRestore;
private boolean fillFood;
private boolean includeStyleBoost=true;
private boolean includeRunePouchForMagic=false;
private int inventoryTarget;
private int loot;
private final List<RequiredItem>requiredItems=new ArrayList<>();
private Builder(){}public Builder coverageKey(String value){coverageKey=value;
return this;
}public Builder method(String value){method=value;
return this;
}public Builder appendTaskMethod(String value){String suffix=clean(value);
if(suffix.isEmpty()){return this;
}String base=clean(method);
if(base.isEmpty()){method=suffix;
return this;
}if(!(base.endsWith(".")||base.endsWith("!")||base.endsWith("?"))){base+=".";
}String combined=base+" "+suffix;
if(combined.length()<=MAX_TASK_METHOD_LENGTH){method=combined;
return this;
}int maximumBase=MAX_TASK_METHOD_LENGTH-suffix.length()-1;
if(maximumBase<=0){method=suffix.substring(0,Math.min(MAX_TASK_METHOD_LENGTH,suffix.length())).trim();
return this;
}int cut=base.lastIndexOf(' ',maximumBase);
if(cut<40){cut=Math.min(maximumBase,base.length());
}base=base.substring(0,cut).trim();
if(!(base.endsWith(".")||base.endsWith("!")||base.endsWith("?"))){base+=".";
}method=(base+" "+suffix).trim();
if(method.length()>MAX_TASK_METHOD_LENGTH){method=method.substring(0,MAX_TASK_METHOD_LENGTH).trim();
}return this;
}public Builder research(String source,String date,boolean isReviewed){researchSource=source;
reviewDate=date;
reviewed=isReviewed;
return this;
}public Builder style(TaskStrategy.CombatStyle value){style=value;
return this;
}public Builder spell(Spellbook value,String spellName){spellbook=value==null?Spellbook.STRATEGY_DEFINED:value;
primarySpell=spellName;
return this;
}public Builder thralls(UtilityRecommendation recommendation){thrallRecommendation=recommendation==null?UtilityRecommendation.NONE:recommendation;
return this;
}public Builder deathCharge(UtilityRecommendation recommendation){deathChargeRecommendation=recommendation==null?UtilityRecommendation.NONE:recommendation;
return this;
}public Builder arceuusUtility(boolean useThralls,boolean useDeathCharge,boolean useWardOfArceuus){thrallRecommendation=useThralls?UtilityRecommendation.RECOMMENDED:UtilityRecommendation.NONE;
deathChargeRecommendation=useDeathCharge?UtilityRecommendation.RECOMMENDED:UtilityRecommendation.NONE;
wardOfArceuus=useWardOfArceuus;
return this;
}public Builder cannon(boolean enabled,int cannonballs){cannonMethod=enabled;
cannonballQuantity=enabled?Math.max(1,cannonballs):0;
return this;
}public Builder control(DamageControl value){control=value==null?DamageControl.STRATEGY_DEFINED:value;
return this;
}public Builder layout(LayoutProfile value){layoutProfile=value==null?LayoutProfile.STANDARD:value;
return this;
}public Builder restore(String primaryFamily,String fallbackFamily){primaryRestoreFamily=primaryFamily;
fallbackRestoreFamily=fallbackFamily;
allowRestoreFallback=fallbackFamily!=null&&!fallbackFamily.trim().isEmpty();
return this;
}public Builder noRestoreFallback(){fallbackRestoreFamily="";
allowRestoreFallback=false;
return this;
}public Builder restoreSlots(int value){restoreSlotsOverride=Math.max(0,value);
return this;
}public Builder food(int value){foodSlotsOverride=Math.max(0,value);
return this;
}public Builder food(String displayName,String...alternatives){foodDisplayName=clean(displayName);
foodAlternatives.clear();
if(alternatives!=null){for(String alternative:alternatives){String value=clean(alternative);
if(!value.isEmpty()){foodAlternatives.add(value);
}}}return this;
}public Builder noInventoryFill(){fillFood=false;
fillRestore=false;
return this;
}public Builder runePouch(boolean required){requireRunePouch=required;
return this;
}public Builder pouchRune(int itemId,String name,int minimumQuantity){pouchRunes.add(new RuneRequirement(itemId,name,minimumQuantity));
return this;
}public Builder fillRestore(){fillRestore=true;
fillFood=false;
return this;
}public Builder fillFood(){fillFood=true;
fillRestore=false;
return this;
}public Builder includeStyleBoost(boolean value){includeStyleBoost=value;
return this;
}public Builder includeRunePouchForMagic(boolean value){includeRunePouchForMagic=value;
return this;
}public Builder inventoryTarget(int value){inventoryTarget=value;
return this;
}public Builder loot(int value){loot=Math.max(0,value);
return this;
}public Builder require(String displayName,int quantity,InventoryGroup group,String...alternatives){requiredItems.add(new RequiredItem(displayName,quantity,1,group,false,alternatives));
return this;
}public Builder ownedOnlyItem(String displayName,int quantity,InventoryGroup group,String...alternatives){requiredItems.add(new RequiredItem(displayName,quantity,1,group,true,alternatives));
return this;
}public Builder requiredSlots(String displayName,int slotCount,InventoryGroup group,String...alternatives){requiredItems.add(new RequiredItem(displayName,1,Math.max(1,slotCount),group,false,alternatives));
return this;
}public MethodRules build(){prepareArceuusPackage();
return new MethodRules(this);
}private void prepareArceuusPackage(){boolean thralls=thrallRecommendation==UtilityRecommendation.RECOMMENDED;
boolean deathCharge=deathChargeRecommendation==UtilityRecommendation.RECOMMENDED;
boolean ward=wardOfArceuus;
if(!thralls&&!deathCharge&&!ward){return;
}spellbook=Spellbook.ARCEUUS;
requireRunePouch=true;
requireBookOfDead=thralls;
requireDivineRunePouch=false;
minimumMagicLevel=deathCharge?80:thralls?76:73;
if(thralls&&deathCharge&&ward){primarySpell=text(65);
}else if(thralls&&deathCharge){primarySpell=text(66);
}else if(thralls&&ward){primarySpell=text(67);
}else if(deathCharge&&ward){primarySpell=text(68);
}else if(thralls){primarySpell=text(69);
}else if(deathCharge){primarySpell="Death Charge";
}else{primarySpell=text(70);
}pouchRunes.clear();
if(thralls&&deathCharge){boolean tormentedDemonCombatMagic=coverageKey.toLowerCase(java.util.Locale.ENGLISH).contains("tormented demon");
addRune(554,"Fire",tormentedDemonCombatMagic?1000:10);
if(ward){addRune(30843,"Aether",tormentedDemonCombatMagic?1000:6);
}else{addRune(564,"Cosmic",tormentedDemonCombatMagic?500:1);
addRune(566,"Soul",tormentedDemonCombatMagic?500:1);
}addRune(565,"Blood",tormentedDemonCombatMagic?500:6);
addRune(560,"Death",tormentedDemonCombatMagic?500:1);
if(ward){addRune(561,"Nature",2);
}return;
}if(thralls){addRune(554,"Fire",10);
addRune(565,"Blood",5);
if(ward){addRune(30843,"Aether",5);
addRune(561,"Nature",2);
}else{addRune(564,"Cosmic",1);
}return;
}if(deathCharge){addRune(565,"Blood",1);
addRune(560,"Death",1);
if(ward){addRune(30843,"Aether",5);
addRune(561,"Nature",2);
}else{addRune(566,"Soul",1);
}return;
}addRune(566,"Soul",4);
addRune(561,"Nature",2);
addRune(564,"Cosmic",1);
}private void addRune(int itemId,String name,int minimumQuantity){pouchRunes.add(new RuneRequirement(itemId,name,minimumQuantity));
}}}
