package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.Locale;
class PotionPolicy{static final String EXTENDED_STAMINA_DISPLAY="Extended stamina potion";
static final String EXTENDED_ANTIVENOM_DISPLAY="Extended anti-venom+";
static final String EXTENDED_ANTIFIRE_DISPLAY="Extended antifire";
static final String EXTENDED_SUPER_ANTIFIRE_DISPLAY="Extended super antifire";
static final String GOADING_DISPLAY="Goading potion";
private PotionPolicy(){}static String[]staminaAlternatives(){return new String[]{"extended stamina potion","stamina potion"};
}static String[]goadingAlternatives(){return new String[]{"goading potion"};
}static String[]antivenomAlternatives(){return new String[]{text(72),"anti venom plus","anti venom"};
}static String[]rangedBoostAlternatives(TaskStrategy.CostPolicy costPolicy){if(costPolicy==TaskStrategy.CostPolicy.MAX_DPS){return new String[]{text(73),text(74),"bastion potion","ranging potion"};
}return new String[]{"ranging potion","bastion potion",text(74),text(73)};
}static String[]meleeBoostAlternatives(TaskStrategy.CostPolicy costPolicy){return costPolicy==TaskStrategy.CostPolicy.MAX_DPS?new String[]{text(75),"super combat potion"}:new String[]{"super combat potion",text(75)};
}static String[]magicBoostAlternatives(){return new String[]{"saturated heart","imbued heart","forgotten brew",text(76),text(77),text(18),"magic potion","ancient brew"};
}static String[]shieldedAntifireAlternatives(){return new String[]{text(78),text(79),text(80),text(81)};
}static String[]fullAntifireAlternatives(){return new String[]{text(80),text(81),text(78)};
}static String[]potionOnlyAntifireAlternatives(){return new String[]{text(80),text(81)};
}static int effectiveDoseUnits(String potionFamily,int doses){int safeDoses=Math.max(0,Math.min(4,doses));
return isDoubleDurationFamily(potionFamily)?safeDoses*2:safeDoses;
}private static boolean isDoubleDurationFamily(String value){String family=normalize(value);
return family.equals("extended stamina potion")||family.equals(text(72))||family.equals(text(78))||family.equals(text(80));
}private static String normalize(String value){return value==null?"":value.toLowerCase(Locale.ENGLISH).replace("+"," plus ").replaceAll(text(9)," ").replaceAll("\\s+"," ").trim();
}}
