package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
@Getter public final class RouteCheck{public enum Kind{ALWAYS,WORLD_AREA,TEMPLATE_AREA,COORDINATE_LAYER_TRANSITION,TRACKED_OBJECT_ACTION,OBSERVED_OBJECT_INTERACTION,VISIBLE_WIDGET_COMPONENT,VISIBLE_WIDGET_GROUP,EXACT_NPC,ANY_OF,ALL_OF}private static final RouteCheck ALWAYS=new RouteCheck(Kind.ALWAYS,null,null,null,null,-1,Collections.emptySet(),Collections.emptyList());
private final Kind kind;
private final SpatialArea area;
private final CoordinateLayer sourceLayer;
private final CoordinateLayer destinationLayer;
private final ObjectActionSpec objectActionSpec;
private final int widgetId;
private final Set<String>npcs;
private final List<RouteCheck>children;
private RouteCheck(Kind kind,SpatialArea area,CoordinateLayer sourceLayer,CoordinateLayer destinationLayer,ObjectActionSpec objectActionSpec,int widgetId,Set<String>npcs,List<RouteCheck>children){this.kind=Objects.requireNonNull(kind);
this.area=area;
this.sourceLayer=sourceLayer;
this.destinationLayer=destinationLayer;
this.objectActionSpec=objectActionSpec;
this.widgetId=widgetId;
this.npcs=immutableSet(npcs);
this.children=immutableList(children);
}public static RouteCheck always(){return ALWAYS;
}public static RouteCheck worldArea(SpatialArea area){return spatial(Kind.WORLD_AREA,area,RouteEvidence.CoordinateSpace.WORLD);
}public static RouteCheck templateArea(SpatialArea area){return spatial(Kind.TEMPLATE_AREA,area,RouteEvidence.CoordinateSpace.TEMPLATE);
}private static RouteCheck spatial(Kind kind,SpatialArea area,RouteEvidence.CoordinateSpace requiredSpace){Objects.requireNonNull(area,"area");
if(area.getCoordinateSpace()!=requiredSpace){throw new IllegalArgumentException(kind+" requires a "+requiredSpace+" area");
}return new RouteCheck(kind,area,null,null,null,-1,Collections.emptySet(),Collections.emptyList());
}public static RouteCheck coordinateLayerTransition(CoordinateLayer sourceLayer,CoordinateLayer destinationLayer){Objects.requireNonNull(sourceLayer,"sourceLayer");
Objects.requireNonNull(destinationLayer,"destinationLayer");
if(sourceLayer.getCoordinateSpace()!=destinationLayer.getCoordinateSpace()){throw new IllegalArgumentException(text(155));
}if(sourceLayer.equals(destinationLayer)){throw new IllegalArgumentException(text(156));
}return new RouteCheck(Kind.COORDINATE_LAYER_TRANSITION,null,sourceLayer,destinationLayer,null,-1,Collections.emptySet(),Collections.emptyList());
}public static RouteCheck trackedObjectAction(ObjectActionSpec spec){return objectAction(Kind.TRACKED_OBJECT_ACTION,spec);
}public static RouteCheck observedObjectInteraction(ObjectActionSpec spec){return objectAction(Kind.OBSERVED_OBJECT_INTERACTION,spec);
}private static RouteCheck objectAction(Kind kind,ObjectActionSpec spec){return new RouteCheck(kind,null,null,null,Objects.requireNonNull(spec,"spec"),-1,Collections.emptySet(),Collections.emptyList());
}public static RouteCheck visibleWidgetComponent(int componentId){return widget(Kind.VISIBLE_WIDGET_COMPONENT,componentId);
}public static RouteCheck visibleWidgetGroup(int groupId){return widget(Kind.VISIBLE_WIDGET_GROUP,groupId);
}private static RouteCheck widget(Kind kind,int id){if(id<0){throw new IllegalArgumentException(text(157));
}return new RouteCheck(kind,null,null,null,null,id,Collections.emptySet(),Collections.emptyList());
}public static RouteCheck exactNpc(String...npcNames){return exactNpc(Arrays.asList(npcNames));
}public static RouteCheck exactNpc(Collection<String>npcNames){Set<String>normalized=normalizedStrings(npcNames);
if(normalized.isEmpty()){throw new IllegalArgumentException(text(158));
}return new RouteCheck(Kind.EXACT_NPC,null,null,null,null,-1,normalized,Collections.emptyList());
}public static RouteCheck anyOf(RouteCheck...predicates){return composite(Kind.ANY_OF,Arrays.asList(predicates));
}public static RouteCheck anyOf(Collection<RouteCheck>predicates){return composite(Kind.ANY_OF,predicates);
}public static RouteCheck allOf(RouteCheck...predicates){return composite(Kind.ALL_OF,Arrays.asList(predicates));
}public static RouteCheck allOf(Collection<RouteCheck>predicates){return composite(Kind.ALL_OF,predicates);
}private static RouteCheck composite(Kind kind,Collection<RouteCheck>predicates){if(predicates==null||predicates.isEmpty()){throw new IllegalArgumentException(kind+text(159));
}List<RouteCheck>copy=new ArrayList<>();
for(RouteCheck predicate:predicates){copy.add(Objects.requireNonNull(predicate,"predicate"));
}if(copy.size()==1){return copy.get(0);
}return new RouteCheck(kind,null,null,null,null,-1,Collections.emptySet(),copy);
}public boolean matches(RouteEvidence evidence){if(evidence==null){return false;
}switch(kind){case ALWAYS:return true;
case WORLD_AREA:case TEMPLATE_AREA:return area.contains(evidence);
case COORDINATE_LAYER_TRANSITION:return matchesLayerTransition(evidence);
case TRACKED_OBJECT_ACTION:return matchesObjectAction(evidence.getTrackedObjectActions());
case OBSERVED_OBJECT_INTERACTION:return matchesObjectAction(evidence.getObservedObjectInteractions());
case VISIBLE_WIDGET_COMPONENT:return evidence.getVisibleWidgetComponents().contains(widgetId);
case VISIBLE_WIDGET_GROUP:return evidence.getVisibleWidgetGroups().contains(widgetId);
case EXACT_NPC:return!Collections.disjoint(npcs,evidence.getNpcs());
case ANY_OF:for(RouteCheck child:children){if(child.matches(evidence)){return true;
}}return false;
case ALL_OF:for(RouteCheck child:children){if(!child.matches(evidence)){return false;
}}return true;
default:return false;
}}public boolean containsKind(Kind expected){if(kind==expected){return true;
}for(RouteCheck child:children){if(child.containsKind(expected)){return true;
}}return false;
}public boolean canMatchObservedInteractionAlone(){switch(kind){case ALWAYS:case OBSERVED_OBJECT_INTERACTION:return true;
case ANY_OF:for(RouteCheck child:children){if(child.canMatchObservedInteractionAlone()){return true;
}}return false;
case ALL_OF:for(RouteCheck child:children){if(!child.canMatchObservedInteractionAlone()){return false;
}}return true;
default:return false;
}}public boolean containsSpatialResultOutside(Collection<WorldPoint>approachPoints,int approachRadius){if(kind==Kind.WORLD_AREA||kind==Kind.TEMPLATE_AREA){if(area==null){return false;
}if(area.getCoordinateSpace()==RouteEvidence.CoordinateSpace.TEMPLATE){return true;
}if(approachPoints==null||approachPoints.isEmpty()){return true;
}for(WorldPoint approachPoint:approachPoints){if(area.intersectsApproach(approachPoint,approachRadius)){return false;
}}return true;
}for(RouteCheck child:children){if(child.containsSpatialResultOutside(approachPoints,approachRadius)){return true;
}}return false;
}private boolean matchesLayerTransition(RouteEvidence evidence){RouteEvidence.CoordinateSpace space=sourceLayer.getCoordinateSpace();
return sourceLayer.contains(evidence.previousPoint(space))&&destinationLayer.contains(evidence.point(space));
}private boolean matchesObjectAction(Set<RouteEvidence.ObjectAction>observations){for(RouteEvidence.ObjectAction observation:observations){if(objectActionSpec.matches(observation)){return true;
}}return false;
}private static<T>Set<T>immutableSet(Set<T>source){if(source==null||source.isEmpty()){return Collections.emptySet();
}return Collections.unmodifiableSet(new LinkedHashSet<>(source));
}private static<T>List<T>immutableList(List<T>source){if(source==null||source.isEmpty()){return Collections.emptyList();
}return Collections.unmodifiableList(new ArrayList<>(source));
}private static Set<String>normalizedStrings(Collection<String>source){if(source==null||source.isEmpty()){return Collections.emptySet();
}Set<String>result=new LinkedHashSet<>();
for(String value:source){String normalized=RouteEvidence.normalize(value);
if(!normalized.isEmpty()){result.add(normalized);
}}return result;
}@Getter public static final class SpatialArea{private final RouteEvidence.CoordinateSpace coordinateSpace;
private final int minX;
private final int maxX;
private final int minY;
private final int maxY;
private final int plane;
private SpatialArea(RouteEvidence.CoordinateSpace coordinateSpace,int minX,int maxX,int minY,int maxY,int plane){this.coordinateSpace=Objects.requireNonNull(coordinateSpace);
if(minX>maxX||minY>maxY||plane<0){throw new IllegalArgumentException(text(160));
}this.minX=minX;
this.maxX=maxX;
this.minY=minY;
this.maxY=maxY;
this.plane=plane;
}public static SpatialArea world(int minX,int maxX,int minY,int maxY,int plane){return new SpatialArea(RouteEvidence.CoordinateSpace.WORLD,minX,maxX,minY,maxY,plane);
}public static SpatialArea template(int minX,int maxX,int minY,int maxY,int plane){return new SpatialArea(RouteEvidence.CoordinateSpace.TEMPLATE,minX,maxX,minY,maxY,plane);
}public static SpatialArea aroundWorld(WorldPoint center,int xRadius,int yRadius){return around(RouteEvidence.CoordinateSpace.WORLD,center,xRadius,yRadius);
}public static SpatialArea aroundTemplate(WorldPoint center,int xRadius,int yRadius){return around(RouteEvidence.CoordinateSpace.TEMPLATE,center,xRadius,yRadius);
}private static SpatialArea around(RouteEvidence.CoordinateSpace coordinateSpace,WorldPoint center,int xRadius,int yRadius){Objects.requireNonNull(center,"center");
if(xRadius<0||yRadius<0){throw new IllegalArgumentException(text(161));
}return new SpatialArea(coordinateSpace,center.getX()-xRadius,center.getX()+xRadius,center.getY()-yRadius,center.getY()+yRadius,center.getPlane());
}public boolean contains(RouteEvidence evidence){return evidence!=null&&contains(evidence.point(coordinateSpace));
}public boolean contains(WorldPoint point){return point!=null&&point.getPlane()==plane&&point.getX()>=minX&&point.getX()<=maxX&&point.getY()>=minY&&point.getY()<=maxY;
}private boolean intersectsApproach(WorldPoint point,int radius){if(point==null||point.getPlane()!=plane){return false;
}int safeRadius=Math.max(0,radius);
return point.getX()+safeRadius>=minX&&point.getX()-safeRadius<=maxX&&point.getY()+safeRadius>=minY&&point.getY()-safeRadius<=maxY;
}}@Getter public static final class CoordinateLayer{private final RouteEvidence.CoordinateSpace coordinateSpace;
private final int plane;
private final Set<Integer>regionIds;
private CoordinateLayer(RouteEvidence.CoordinateSpace coordinateSpace,int plane,Set<Integer>regionIds){this.coordinateSpace=Objects.requireNonNull(coordinateSpace);
if(plane<0||regionIds==null||regionIds.isEmpty()){throw new IllegalArgumentException(text(162));
}this.plane=plane;
this.regionIds=immutableSet(regionIds);
}public static CoordinateLayer worldRegions(int plane,int...regionIds){return regions(RouteEvidence.CoordinateSpace.WORLD,plane,regionIds);
}public static CoordinateLayer templateRegions(int plane,int...regionIds){return regions(RouteEvidence.CoordinateSpace.TEMPLATE,plane,regionIds);
}private static CoordinateLayer regions(RouteEvidence.CoordinateSpace coordinateSpace,int plane,int...regionIds){if(regionIds==null||regionIds.length==0){throw new IllegalArgumentException(text(163));
}Set<Integer>reviewed=new LinkedHashSet<>();
for(int regionId:regionIds){if(regionId<0){throw new IllegalArgumentException(text(164));
}reviewed.add(regionId);
}return new CoordinateLayer(coordinateSpace,plane,reviewed);
}public boolean contains(WorldPoint point){return point!=null&&point.getPlane()==plane&&regionIds.contains(point.getRegionID());
}@Override public boolean equals(Object other){if(this==other){return true;
}if(!(other instanceof CoordinateLayer)){return false;
}CoordinateLayer that=(CoordinateLayer)other;
return plane==that.plane&&coordinateSpace==that.coordinateSpace&&regionIds.equals(that.regionIds);
}@Override public int hashCode(){return Objects.hash(coordinateSpace,plane,regionIds);
}}@Getter public static final class ObjectActionSpec{private final Set<Integer>objectIds;
private final Set<String>objectNames;
private final Set<String>actions;
private ObjectActionSpec(Collection<Integer>objectIds,Collection<String>objectNames,Collection<String>actions){Set<Integer>reviewedIds=new LinkedHashSet<>();
if(objectIds!=null){for(Integer objectId:objectIds){if(objectId==null||objectId<=0){throw new IllegalArgumentException(text(165));
}reviewedIds.add(objectId);
}}this.objectIds=immutableSet(reviewedIds);
this.objectNames=immutableSet(normalizedStrings(objectNames));
this.actions=immutableSet(normalizedStrings(actions));
if(this.objectIds.isEmpty()&&this.objectNames.isEmpty()){throw new IllegalArgumentException(text(166));
}if(this.actions.isEmpty()){throw new IllegalArgumentException(text(167));
}}public static ObjectActionSpec named(String objectName,String...actions){return new ObjectActionSpec(Collections.emptySet(),Collections.singleton(objectName),Arrays.asList(actions));
}public static ObjectActionSpec identified(int objectId,String...actions){return new ObjectActionSpec(Collections.singleton(objectId),Collections.emptySet(),Arrays.asList(actions));
}public static ObjectActionSpec reviewed(Collection<Integer>objectIds,Collection<String>objectNames,Collection<String>actions){return new ObjectActionSpec(objectIds,objectNames,actions);
}private boolean matches(RouteEvidence.ObjectAction observation){boolean identityMatches=(!objectIds.isEmpty()&&objectIds.contains(observation.getObjectId()))||(!objectNames.isEmpty()&&objectNames.contains(observation.getObjectName()));
return identityMatches&&actions.contains(observation.getAction());
}}}
