package com.slayerplus;
import static com.slayerplus.Text.text;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
public final class RouteCatalog{public static final int CATALOG_REVISION=15;
public enum RouteMode{OPEN_WORLD,VERIFIED_INTERIOR,TRANSPORT_CHAIN_INTERIOR,STAGED_INTERIOR,ACCESS_THEN_NPC,NPC_ONLY,BOSS_OPEN_WORLD,BOSS_VERIFIED_INTERIOR,BOSS_TRANSPORT_CHAIN_INTERIOR,BOSS_STAGED_INTERIOR,BOSS_ACCESS_THEN_NPC,BOSS_NPC_ONLY}@Getter public static final class TransitionSpec{private final WorldPoint approachPoint;
private final Set<String>objectNameHints;
private final Set<String>actions;
private final int searchRadius;
private TransitionSpec(WorldPoint approachPoint,Set<String>objectNameHints,Set<String>actions,int searchRadius){this.approachPoint=approachPoint;
this.objectNameHints=Collections.unmodifiableSet(new LinkedHashSet<>(objectNameHints));
this.actions=Collections.unmodifiableSet(new LinkedHashSet<>(actions));
this.searchRadius=Math.max(1,searchRadius);
}public boolean hasObjectNameHints(){return!objectNameHints.isEmpty();
}public boolean matchesObjectName(String objectName){if(objectNameHints.isEmpty()){return true;
}String value=normalize(objectName);
for(String hint:objectNameHints){if(!hint.isEmpty()&&value.contains(hint)){return true;
}}return false;
}public boolean matchesAction(String action){return actions.contains(normalize(action));
}}public static final class EncounterArea{private final WorldPoint center;
private final int xRadius;
private final int yRadius;
private EncounterArea(WorldPoint center,int xRadius,int yRadius){this.center=center;
this.xRadius=Math.max(1,xRadius);
this.yRadius=Math.max(1,yRadius);
}public boolean contains(WorldPoint point){return point!=null&&center!=null&&point.getPlane()==center.getPlane()&&sameCoordinateLayer(point,center)&&Math.abs(point.getX()-center.getX())<=xRadius&&Math.abs(point.getY()-center.getY())<=yRadius;
}}@Getter public static final class RouteProfile{private static final int ENCOUNTER_REGION_RADIUS=192;
private final String assignment;
private final String location;
private final WorldPoint primaryDestination;
private final WorldPoint surfaceAccess;
private final TransitionSpec transitionSpec;
private final EncounterArea encounterArea;
private final String transitionInstruction;
private final String positioningNote;
private final RouteMode mode;
private final Set<String>npcNames;
private final int targetRadius;
private final int arrivalRadius;
private RouteProfile(String assignment,String location,WorldPoint primaryDestination,RouteMode mode,Set<String>npcNames,int targetRadius,int arrivalRadius){this(assignment,location,primaryDestination,null,"","",mode,npcNames,targetRadius,arrivalRadius);
}private RouteProfile(String assignment,String location,WorldPoint primaryDestination,WorldPoint surfaceAccess,String transitionInstruction,String positioningNote,RouteMode mode,Set<String>npcNames,int targetRadius,int arrivalRadius){this.assignment=assignment==null?"":assignment.trim();
this.location=location==null?"":location.trim();
this.primaryDestination=primaryDestination;
this.surfaceAccess=surfaceAccess;
this.transitionSpec=surfaceAccess==null?null:transitionSpecFor(this.location,surfaceAccess);
this.encounterArea=primaryDestination==null?null:new EncounterArea(primaryDestination,ENCOUNTER_REGION_RADIUS,ENCOUNTER_REGION_RADIUS);
this.transitionInstruction=transitionInstruction==null?"":transitionInstruction.trim();
this.positioningNote=positioningNote==null?"":positioningNote.trim();
this.mode=mode;
this.npcNames=Collections.unmodifiableSet(new LinkedHashSet<>(npcNames));
this.targetRadius=Math.max(0,targetRadius);
this.arrivalRadius=Math.max(1,arrivalRadius);
if(isStaged()){validateStagedSurfaceAccess();
}}public String getTaskName(){return assignment;
}private void validateStagedSurfaceAccess(){if(surfaceAccess==null){throw new IllegalStateException(text(120)+assignment+" @ "+location);
}if(surfaceAccess.getY()>=6400){throw new IllegalStateException(text(121)+assignment+" @ "+location+" -> "+surfaceAccess);
}if(primaryDestination!=null&&surfaceAccess.equals(primaryDestination)){throw new IllegalStateException(text(122)+assignment+" @ "+location);
}}public boolean isVerifiedInterior(){return mode==RouteMode.VERIFIED_INTERIOR||mode==RouteMode.TRANSPORT_CHAIN_INTERIOR||mode==RouteMode.STAGED_INTERIOR||mode==RouteMode.BOSS_VERIFIED_INTERIOR||mode==RouteMode.BOSS_TRANSPORT_CHAIN_INTERIOR||mode==RouteMode.BOSS_STAGED_INTERIOR;
}public boolean isStaged(){return mode==RouteMode.STAGED_INTERIOR||mode==RouteMode.BOSS_STAGED_INTERIOR;
}public boolean isAccessThenNpc(){return mode==RouteMode.ACCESS_THEN_NPC||mode==RouteMode.BOSS_ACCESS_THEN_NPC;
}public boolean requiresLoadedNpc(){return mode==RouteMode.NPC_ONLY||mode==RouteMode.BOSS_NPC_ONLY;
}public boolean hasStaticDestination(){return primaryDestination!=null;
}public boolean isBoss(){return mode==RouteMode.BOSS_OPEN_WORLD||mode==RouteMode.BOSS_ACCESS_THEN_NPC||mode==RouteMode.BOSS_VERIFIED_INTERIOR||mode==RouteMode.BOSS_TRANSPORT_CHAIN_INTERIOR||mode==RouteMode.BOSS_STAGED_INTERIOR||mode==RouteMode.BOSS_NPC_ONLY;
}public boolean insideArea(WorldPoint here){if(here==null||primaryDestination==null){return false;
}return encounterArea!=null&&encounterArea.contains(here);
}public boolean shouldRouteToSurfaceAccess(WorldPoint here){if(!isStaged()||surfaceAccess==null){return false;
}if(here==null){return true;
}if(!sameCoordinateLayer(surfaceAccess,primaryDestination)){return sameCoordinateLayer(here,surfaceAccess);
}return!insideArea(here);
}public boolean isPlausibleLearnedCheckpoint(WorldPoint checkpoint){if(checkpoint==null||checkpoint.getPlane()<0||checkpoint.getPlane()>3||checkpoint.getX()<=0||checkpoint.getY()<=0){return false;
}if(isStaged()&&primaryDestination!=null){return encounterArea!=null&&encounterArea.contains(checkpoint);
}return true;
}public WorldPoint getRouteDestination(WorldPoint here){return shouldRouteToSurfaceAccess(here)?surfaceAccess:primaryDestination;
}public int getArrivalRadius(){return arrivalRadius;
}public int getArrivalRadius(WorldPoint here){return shouldRouteToSurfaceAccess(here)?ACCESS_ARRIVAL_RADIUS:arrivalRadius;
}public Set<WorldPoint>getRouteTargets(){return targetArea(primaryDestination,targetRadius);
}public Set<WorldPoint>getRouteTargets(WorldPoint here){WorldPoint destination=getRouteDestination(here);
if(destination!=null&&destination.equals(surfaceAccess)&&isStaged()&&!usesReachableSurfaceApproachArea()){return Collections.singleton(destination);
}int radius=destination!=null&&destination.equals(surfaceAccess)?ACCESS_TARGET_RADIUS:targetRadius;
return targetArea(destination,radius);
}private boolean usesReachableSurfaceApproachArea(){return normalize(location).equals(text(123));
}public boolean matchesNpc(String npcName){String normalized=normalizeNpcName(npcName);
return!normalized.isEmpty()&&npcNames.contains(normalized);
}public Set<String>getNpcNames(){return npcNames;
}}private static final int INTERIOR_TARGET_RADIUS=2;
private static final int ACCESS_TARGET_RADIUS=1;
private static final int INTERIOR_ARRIVAL_RADIUS=14;
private static final int ACCESS_ARRIVAL_RADIUS=2;
private static final Set<String>INFERNO_ENTRY_NPC_NAMES=Collections.unmodifiableSet(new LinkedHashSet<>(Arrays.asList(text(124))));
private static final WorldPoint INFERNO_ENTRY_APPROACH=new WorldPoint(2496,5115,0);
private static final List<String[]>RESOURCE_ROWS=loadResourceRows();
private static final Map<String,WorldPoint>ACCESS_ROUTES=loadAccessRoutes();
private static final ProfileData PROFILE_DATA=loadProfiles();
private static final Map<String,RouteProfile>STANDARD_PROFILES=PROFILE_DATA.standardProfiles;
private static final Map<String,RouteProfile>BOSS_PROFILES=PROFILE_DATA.bossProfiles;
private static final Map<String,WorldPoint>CANNON_POSITIONS=createCannonPositions();
private static final Map<String,WorldPoint>BARRAGE_POSITIONS=createBarragePositions();
private RouteCatalog(){}public static boolean requiresPreparationBank(String assignment,String location,boolean bossVariant){return bossVariant&&normalizeTaskKey(assignment).equals(text(2))&&normalize(location).equals("inferno");
}public static Set<String>getPreparationEntryNpcNames(String assignment,String location,boolean bossVariant){return requiresPreparationBank(assignment,location,bossVariant)?INFERNO_ENTRY_NPC_NAMES:Collections.emptySet();
}public static WorldPoint getPreparationEntryApproachTarget(String assignment,String location,boolean bossVariant){return requiresPreparationBank(assignment,location,bossVariant)?INFERNO_ENTRY_APPROACH:null;
}public static RouteProfile resolve(String assignment,String location,boolean bossVariant){String task=normalizeTaskKey(assignment);
String area=normalize(location);
if(task.isEmpty()||area.isEmpty()){return null;
}String key=profileKey(task,area);
if(bossVariant){RouteProfile reviewedBoss=BOSS_PROFILES.get(key);
if(reviewedBoss!=null){return reviewedBoss;
}WorldPoint bossAccess=ACCESS_ROUTES.get(area);
if(bossAccess!=null){return bossAccessProfile(assignment,location,bossAccess,defaultNpcAliases(assignment));
}return npcOnlyProfile(assignment,location,defaultNpcAliases(assignment),true);
}RouteProfile reviewed=STANDARD_PROFILES.get(key);
if(reviewed!=null){return reviewed;
}WorldPoint access=ACCESS_ROUTES.get(area);
if(access==null){return npcOnlyProfile(assignment,location,defaultNpcAliases(assignment),false);
}return accessProfile(assignment,location,access,defaultNpcAliases(assignment));
}public static WorldPoint find(String assignment,String location){RouteProfile profile=resolve(assignment,location,false);
return profile==null?null:profile.getPrimaryDestination();
}public static WorldPoint find(String location){return ACCESS_ROUTES.get(normalize(location));
}public static boolean hasTaskSpecificRoute(String assignment,String location){RouteProfile profile=resolve(assignment,location,false);
return profile!=null&&profile.isVerifiedInterior();
}public static boolean prefersWorldMapEntranceIcon(String location){String area=normalize(location);
return area.contains("dungeon")||area.contains("cave")||area.contains("cavern")||area.contains("catacombs")||area.contains("tunnel")||area.contains("lair")||area.contains("prison")||area.contains("vault")||area.contains("chasm")||area.contains("stronghold")||area.contains("slayer tower")||area.contains("cove");
}public static WorldPoint findCannonPosition(String assignment,String location){String task=normalizeTaskKey(assignment);
String area=normalize(location);
if(task.isEmpty()||area.isEmpty()){return null;
}return CANNON_POSITIONS.get(profileKey(task,area));
}public static WorldPoint findBarragePosition(String assignment,String location){String task=normalizeTaskKey(assignment);
String area=normalize(location);
if(task.isEmpty()||area.isEmpty()){return null;
}return BARRAGE_POSITIONS.get(profileKey(task,area));
}public static boolean isWilderness(String value){String normalized=normalize(value);
return normalized.contains("wilderness")||normalized.contains("revenant")||normalized.contains("forinthry")||normalized.equals("hunter s end")||normalized.equals(text(125))||normalized.equals(text(126))||normalized.equals("web chasm")||normalized.equals("silk chasm")||normalized.equals("skeletal tomb")||normalized.equals(text(127));
}public static Set<WorldPoint>targetArea(WorldPoint center,int radius){if(center==null){return Collections.emptySet();
}int safeRadius=Math.max(0,radius);
Set<WorldPoint>targets=new LinkedHashSet<>();
for(int dx=-safeRadius;
dx<=safeRadius;
dx++){for(int dy=-safeRadius;
dy<=safeRadius;
dy++){targets.add(new WorldPoint(center.getX()+dx,center.getY()+dy,center.getPlane()));
}}return Collections.unmodifiableSet(targets);
}private static List<String[]>loadResourceRows(){List<String[]>rows=ResourceTable.decodedRows(text(128),5,13);
for(String[]fields:rows){if((fields[0].equals("A"))!=(fields.length==5)){throw new IllegalStateException(text(129)+fields[0]);
}}return rows;
}private static Map<String,WorldPoint>loadAccessRoutes(){Map<String,WorldPoint>routes=new LinkedHashMap<>();
for(String[]fields:RESOURCE_ROWS){if(fields[0].equals("A")){putAccess(routes,fields[1],integer(fields[2]),integer(fields[3]),integer(fields[4]));
}}return Collections.unmodifiableMap(routes);
}private static ProfileData loadProfiles(){Map<String,RouteProfile>standard=new LinkedHashMap<>();
Map<String,RouteProfile>bosses=new LinkedHashMap<>();
for(String[]fields:RESOURCE_ROWS){if(fields[0].equals("S")||fields[0].equals("B")){applyProfileRow(fields[0].equals("B")?bosses:standard,fields);
}}addFightCaveProfile(bosses);
return new ProfileData(Collections.unmodifiableMap(standard),Collections.unmodifiableMap(bosses));
}private static void applyProfileRow(Map<String,RouteProfile>profiles,String[]fields){String helper=fields[1];
String task=fields[2];
String location=fields[3];
int[]access=coordinates(fields,4);
int[]destination=coordinates(fields,7);
String transition=fields[10];
String note=fields[11];
Set<String>npcs=npcAliases(task,splitNames(fields[12]));
WorldPoint accessPoint=point(access);
WorldPoint destinationPoint=point(destination);
RouteMode mode;
int targetRadius=INTERIOR_TARGET_RADIUS;
int arrivalRadius=INTERIOR_ARRIVAL_RADIUS;
switch(helper){case "putOpenWorld":mode=RouteMode.OPEN_WORLD;
accessPoint=null;
break;
case "putTraversableInterior":mode=RouteMode.TRANSPORT_CHAIN_INTERIOR;
accessPoint=null;
break;
case "putStagedInterior":mode=RouteMode.STAGED_INTERIOR;
break;
case "putStagedInteriorWide":mode=RouteMode.STAGED_INTERIOR;
targetRadius=8;
break;
case "putStagedInteriorFromAccess":case "putStagedInteriorFromAccessWithPositioning":mode=RouteMode.STAGED_INTERIOR;
accessPoint=requiredAccess(location);
if(sameCoordinateLayer(accessPoint,destinationPoint)){throw new IllegalStateException(text(130)+task+" @ "+location);
}transition=reviewedTransition(location,false);
break;
case "putAccessProfile":accessPoint=requiredAccess(location);
destinationPoint=accessPoint;
case "putAccessProfileAt":mode=RouteMode.ACCESS_THEN_NPC;
destinationPoint=accessPoint;
transition=reviewedTransition(location,false);
targetRadius=ACCESS_TARGET_RADIUS;
arrivalRadius=ACCESS_ARRIVAL_RADIUS;
break;
case "putBossOpenWorld":mode=RouteMode.BOSS_OPEN_WORLD;
accessPoint=null;
break;
case "putBossInterior":mode=RouteMode.BOSS_VERIFIED_INTERIOR;
accessPoint=null;
break;
case "putBossTraversableInterior":mode=RouteMode.BOSS_TRANSPORT_CHAIN_INTERIOR;
accessPoint=null;
break;
case "putBossStagedInteriorWide":mode=RouteMode.BOSS_STAGED_INTERIOR;
targetRadius=8;
break;
case "putBossStagedInteractionCheckpoint":mode=RouteMode.BOSS_STAGED_INTERIOR;
accessPoint=requiredAccess(location);
transition="Enter "+location+text(131);
targetRadius=0;
arrivalRadius=2;
break;
case "putBossAccessProfile":mode=RouteMode.BOSS_ACCESS_THEN_NPC;
accessPoint=requiredAccess(location);
destinationPoint=accessPoint;
transition=reviewedTransition(location,true);
targetRadius=ACCESS_TARGET_RADIUS;
arrivalRadius=ACCESS_ARRIVAL_RADIUS;
break;
default:throw new IllegalStateException(text(132)+helper);
}putProfile(profiles,new RouteProfile(task,location,destinationPoint,accessPoint,transition,note,mode,npcs,targetRadius,arrivalRadius));
}private static WorldPoint point(int[]coordinates){return coordinates[0]==0?null:new WorldPoint(coordinates[0],coordinates[1],coordinates[2]);
}private static WorldPoint requiredAccess(String location){WorldPoint access=ACCESS_ROUTES.get(normalize(location));
if(access==null){throw new IllegalStateException(text(133)+location);
}return access;
}private static String reviewedTransition(String location,boolean boss){return "Use the reviewed "+location+(boss?" access route":" transition")+text(134)+(boss?"boss.":"task NPC.");
}private static void addFightCaveProfile(Map<String,RouteProfile>profiles){WorldPoint entrance=new WorldPoint(2439,5172,0);
putProfile(profiles,new RouteProfile(text(135),text(136),entrance,entrance,"","",RouteMode.BOSS_VERIFIED_INTERIOR,npcAliases(text(135),text(135)),INTERIOR_TARGET_RADIUS,INTERIOR_ARRIVAL_RADIUS));
}private static int[]coordinates(String[]fields,int offset){if(fields[offset].isEmpty()){return new int[]{0,0,0};
}return new int[]{integer(fields[offset]),integer(fields[offset+1]),integer(fields[offset+2])};
}private static int integer(String value){try{return Integer.parseInt(value);
}catch(NumberFormatException ex){throw new IllegalStateException("Invalid route coordinate "+value,ex);
}}private static String[]splitNames(String value){return value.isEmpty()?new String[0]:value.split("\\|",-1);
}private static final class ProfileData{private final Map<String,RouteProfile>standardProfiles;
private final Map<String,RouteProfile>bossProfiles;
private ProfileData(Map<String,RouteProfile>standardProfiles,Map<String,RouteProfile>bossProfiles){this.standardProfiles=standardProfiles;
this.bossProfiles=bossProfiles;
}}private static Map<String,WorldPoint>createCannonPositions(){Map<String,WorldPoint>positions=new LinkedHashMap<>();
positions.put(profileKey(normalizeTaskKey("Dark beasts"),normalize(text(137))),new WorldPoint(1992,4655,0));
positions.put(profileKey(normalizeTaskKey(text(138)),normalize(text(139))),new WorldPoint(3594,9743,0));
positions.put(profileKey(normalizeTaskKey(text(138)),normalize(text(140))),new WorldPoint(2096,10099,0));
positions.put(profileKey(normalizeTaskKey(text(138)),normalize(text(141))),new WorldPoint(3236,12438,0));
positions.put(profileKey(normalizeTaskKey(text(138)),normalize(text(142))),new WorldPoint(2465,9833,0));
positions.put(profileKey(normalizeTaskKey("Cave horrors"),normalize(text(143))),new WorldPoint(3775,9407,0));
return Collections.unmodifiableMap(positions);
}private static Map<String,WorldPoint>createBarragePositions(){Map<String,WorldPoint>positions=new LinkedHashMap<>();
positions.put(profileKey(normalizeTaskKey("Abyssal demons"),normalize(text(144))),new WorldPoint(1675,10091,0));
return Collections.unmodifiableMap(positions);
}private static RouteProfile accessProfile(String assignment,String location,WorldPoint access,Set<String>aliases){return new RouteProfile(assignment,location,access,access,"Use the reviewed "+location+text(145),"",RouteMode.ACCESS_THEN_NPC,aliases,ACCESS_TARGET_RADIUS,ACCESS_ARRIVAL_RADIUS);
}private static RouteProfile bossAccessProfile(String assignment,String location,WorldPoint access,Set<String>aliases){return new RouteProfile(assignment,location,access,access,"Use the reviewed "+location+text(146),"",RouteMode.BOSS_ACCESS_THEN_NPC,aliases,ACCESS_TARGET_RADIUS,ACCESS_ARRIVAL_RADIUS);
}private static RouteProfile npcOnlyProfile(String assignment,String location,Set<String>aliases,boolean boss){return new RouteProfile(assignment,location,null,boss?RouteMode.BOSS_NPC_ONLY:RouteMode.NPC_ONLY,aliases,0,INTERIOR_ARRIVAL_RADIUS);
}private static void putProfile(Map<String,RouteProfile>profiles,RouteProfile profile){String key=profileKey(normalizeTaskKey(profile.assignment),normalize(profile.location));
if(profiles.put(key,profile)!=null){throw new IllegalStateException(text(147)+profile.assignment+" @ "+profile.location);
}}private static Set<String>npcAliases(String assignment,String...npcNames){Set<String>aliases=defaultNpcAliases(assignment);
if(npcNames!=null){for(String npcName:npcNames){String normalized=normalizeNpcName(npcName);
if(!normalized.isEmpty()){aliases.add(normalized);
}}}return aliases;
}private static Set<String>defaultNpcAliases(String assignment){return new LinkedHashSet<>(SlayerTaskNpcCatalog.aliasesForStandardRoute(assignment));
}private static String normalizeNpcName(String value){return singularTaskName(normalize(value));
}private static String normalizeTaskKey(String value){return singularTaskName(normalize(value));
}private static String singularTaskName(String value){if(value==null||value.isEmpty()){return "";
}if(value.endsWith("wolves")){return value.substring(0,value.length()-6)+"wolf";
}if(value.endsWith("elves")){return value.substring(0,value.length()-5)+"elf";
}if(value.endsWith("dwarves")){return value.substring(0,value.length()-7)+"dwarf";
}if(value.endsWith("men")){return value.substring(0,value.length()-3)+"man";
}if(value.endsWith("ies")&&value.length()>4){return value.substring(0,value.length()-3)+"y";
}if(value.endsWith("s")&&!value.endsWith("ss")&&!value.endsWith("us")&&!value.endsWith("is")&&value.length()>3){return value.substring(0,value.length()-1);
}return value;
}private static String profileKey(String normalizedTask,String normalizedLocation){return normalizedTask+"|"+normalizedLocation;
}private static void putAccess(Map<String,WorldPoint>routes,String name,int x,int y,int plane){String key=normalize(name);
if(key.isEmpty()){throw new IllegalStateException(text(148));
}if(routes.put(key,new WorldPoint(x,y,plane))!=null){throw new IllegalStateException(text(149)+name);
}}private static TransitionSpec transitionSpecFor(String location,WorldPoint approachPoint){Set<String>names=new LinkedHashSet<>();
Set<String>actions=new LinkedHashSet<>();
String area=normalize(location);
if(area.equals(text(150))){names.add("king rada");
names.add("statue");
actions.add("investigate");
return new TransitionSpec(approachPoint,names,actions,12);
}if(area.equals(text(151))){names.add("cave entrance");
names.add("entrance");
actions.add("enter");
return new TransitionSpec(approachPoint,names,actions,12);
}if(area.equals(text(152))){names.add("rowboat");
names.add("rowboat space");
actions.add("travel");
actions.add("row");
actions.add("use");
return new TransitionSpec(approachPoint,names,actions,12);
}if(area.equals(text(123))){names.add("trapdoor");
names.add("trap door");
actions.add("climb down");
return new TransitionSpec(approachPoint,names,actions,10);
}if(area.equals("digsite dungeon")){names.add("winch");
actions.add("operate");
actions.add("use");
actions.add("climb down");
return new TransitionSpec(approachPoint,names,actions,10);
}if(area.equals(text(153))){names.add("lift platform");
actions.add("use");
actions.add("descend");
return new TransitionSpec(approachPoint,names,actions,12);
}actions.add("enter");
actions.add("climb down");
actions.add(text(154));
actions.add("go through");
actions.add("walk through");
actions.add("pass");
actions.add("descend");
actions.add("investigate");
actions.add("use");
return new TransitionSpec(approachPoint,names,actions,24);
}private static boolean sameCoordinateLayer(WorldPoint first,WorldPoint second){if(first==null||second==null){return true;
}return first.getPlane()==second.getPlane()&&(first.getY()>>>12)==(second.getY()>>>12);
}private static String normalize(String value){if(value==null){return "";
}return value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim();
}static Set<String>reviewedAccessLocationsForTest(){return Collections.unmodifiableSet(new LinkedHashSet<>(ACCESS_ROUTES.keySet()));
}static boolean hasExplicitProfileForTest(String assignment,String location,boolean bossVariant){String task=normalizeTaskKey(assignment);
String area=normalize(location);
if(task.isEmpty()||area.isEmpty()){return false;
}return(bossVariant?BOSS_PROFILES:STANDARD_PROFILES).containsKey(profileKey(task,area));
}static Set<String>explicitProfileKeysForTest(boolean bossVariant){return Collections.unmodifiableSet(new LinkedHashSet<>((bossVariant?BOSS_PROFILES:STANDARD_PROFILES).keySet()));
}}
