package com.slayerplus;
import java.util.*;
import net.runelite.api.gameval.ItemID;
class RunePolicy{static final class ResolvedRune{private final int itemId;
private final String name;
private int minimumQuantity;
private ResolvedRune(int itemId,String name,int minimumQuantity){this.itemId=itemId;
this.name=name;
this.minimumQuantity=Math.max(1,minimumQuantity);
}int getItemId(){return itemId;
}String getName(){return name;
}int getMinimumQuantity(){return minimumQuantity;
}}static final class Resolution{private final List<ResolvedRune>runes;
private final List<String>unownedRequirements;
private Resolution(List<ResolvedRune>runes,List<String>unownedRequirements){this.runes=Collections.unmodifiableList(runes);
this.unownedRequirements=Collections.unmodifiableList(unownedRequirements);
}List<ResolvedRune>getRunes(){return runes;
}List<String>getUnownedRequirements(){return unownedRequirements;
}}private RunePolicy(){}static Resolution resolve(List<MethodRules.RuneRequirement>requirements,Map<Integer,Integer>ownedQuantities){if(requirements==null||requirements.isEmpty()){return new Resolution(Collections.emptyList(),Collections.emptyList());
}Map<Integer,ResolvedRune>selected=new LinkedHashMap<>();
List<String>unowned=new ArrayList<>();
for(MethodRules.RuneRequirement requirement:requirements){int selectedId=existingSatisfyingRune(selected.keySet(),requirement.getItemId());
if(selectedId<=0){selectedId=bestOwnedRune(requirement.getItemId(),requirements,ownedQuantities);
}if(selectedId<=0){unowned.add(requirement.getName());
continue;
}ResolvedRune existing=selected.get(selectedId);
if(existing==null){selected.put(selectedId,new ResolvedRune(selectedId,runeName(selectedId),requirement.getMinimumQuantity()));
}else{if(existing.itemId==ItemID.AETHERRUNE){existing.minimumQuantity+=requirement.getMinimumQuantity();
}else{existing.minimumQuantity=Math.max(existing.minimumQuantity,requirement.getMinimumQuantity());
}}}return new Resolution(new ArrayList<>(selected.values()),unowned);
}private static int existingSatisfyingRune(Set<Integer>selectedIds,int requiredId){for(int itemId:selectedIds){if(satisfies(itemId,requiredId)){return itemId;
}}return-1;
}private static int bestOwnedRune(int requiredId,List<MethodRules.RuneRequirement>requirements,Map<Integer,Integer>ownedQuantities){int bestId=-1;
int bestCoverage=-1;
int bestQuantity=-1;
for(int candidateId:candidates(requiredId)){int quantity=ownedQuantities==null?0:ownedQuantities.getOrDefault(candidateId,0);
if(quantity<=0){continue;
}int coverage=0;
for(MethodRules.RuneRequirement requirement:requirements){if(satisfies(candidateId,requirement.getItemId())){coverage++;
}}if(coverage>bestCoverage||(coverage==bestCoverage&&quantity>bestQuantity)||(coverage==bestCoverage&&quantity==bestQuantity&&candidateId==requiredId)){bestId=candidateId;
bestCoverage=coverage;
bestQuantity=quantity;
}}return bestId;
}private static List<Integer>candidates(int requiredId){Set<Integer>values=new LinkedHashSet<>();
values.add(requiredId);
if(requiredId==ItemID.AIRRUNE){values.add(ItemID.MISTRUNE);
values.add(ItemID.DUSTRUNE);
values.add(ItemID.SMOKERUNE);
}else if(requiredId==ItemID.WATERRUNE){values.add(ItemID.MISTRUNE);
values.add(ItemID.MUDRUNE);
values.add(ItemID.STEAMRUNE);
}else if(requiredId==ItemID.EARTHRUNE){values.add(ItemID.DUSTRUNE);
values.add(ItemID.MUDRUNE);
values.add(ItemID.LAVARUNE);
}else if(requiredId==ItemID.FIRERUNE){values.add(ItemID.SMOKERUNE);
values.add(ItemID.STEAMRUNE);
values.add(ItemID.LAVARUNE);
}else if(requiredId==ItemID.COSMICRUNE||requiredId==ItemID.SOULRUNE){values.add(ItemID.AETHERRUNE);
}return new ArrayList<>(values);
}static boolean satisfies(int candidateId,int requiredId){return candidates(requiredId).contains(candidateId);
}private static String runeName(int itemId){if(itemId==ItemID.AIRRUNE)return "Air";
if(itemId==ItemID.WATERRUNE)return "Water";
if(itemId==ItemID.EARTHRUNE)return "Earth";
if(itemId==ItemID.FIRERUNE)return "Fire";
if(itemId==ItemID.MINDRUNE)return "Mind";
if(itemId==ItemID.CHAOSRUNE)return "Chaos";
if(itemId==ItemID.DEATHRUNE)return "Death";
if(itemId==ItemID.BLOODRUNE)return "Blood";
if(itemId==ItemID.COSMICRUNE)return "Cosmic";
if(itemId==ItemID.SOULRUNE)return "Soul";
if(itemId==ItemID.WRATHRUNE)return "Wrath";
if(itemId==ItemID.LAWRUNE)return "Law";
if(itemId==ItemID.NATURERUNE)return "Nature";
if(itemId==ItemID.MISTRUNE)return "Mist";
if(itemId==ItemID.DUSTRUNE)return "Dust";
if(itemId==ItemID.SMOKERUNE)return "Smoke";
if(itemId==ItemID.MUDRUNE)return "Mud";
if(itemId==ItemID.STEAMRUNE)return "Steam";
if(itemId==ItemID.LAVARUNE)return "Lava";
if(itemId==ItemID.AETHERRUNE)return "Aether";
return "Rune";
}}
