package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
import lombok.Setter;
import lombok.experimental.Accessors;
import net.runelite.api.coords.WorldPoint;
import net.runelite.client.eventbus.EventBus;
import net.runelite.client.events.PluginMessage;
public final class ShortestPathBridge{private static final String NAMESPACE="shortestpath";
private static final String PATH_MESSAGE="path";
private static final String CLEAR_MESSAGE="clear";
private static final String INVENTORY_TELEPORTS="Inventory";
private static final String BANK_AND_INVENTORY_TELEPORTS="Inventory and Bank";
private static final int TASK_AREA_UNREACHABLE_DISTANCE=12;
private static final int PREPARATION_BANK_UNREACHABLE_DISTANCE=2;
private static final int PREPARATION_ACCESS_UNREACHABLE_DISTANCE=2;
private static final int LOCAL_TASK_UNREACHABLE_DISTANCE=6;
private static final int MAX_RELEVANT_EDGE_DISTANCE=1_024;
private static final int MAX_RETIRED_REQUESTS=4;
private static final int ENDPOINT_AFFINITY_MARGIN=32;
private final EventBus eventBus;
private final Object requestLock=new Object();
private long nextRequestSequence;
private long acceptedRequestSequence=-1L;
private long reservedRequestSequence=-1L;
private volatile RequestToken activeRequest;
private final Deque<RequestSignature>retiredRequests=new ArrayDeque<>(MAX_RETIRED_REQUESTS);
static final class RequestToken{private final long sequence;
private final RequestSignature signature;
private final Set<WorldPoint>targets;
private final boolean expectsTransportResponse;
private final boolean ambiguityRetryAllowed;
private RequestToken(long sequence,RequestSignature signature,Set<WorldPoint>targets,boolean expectsTransportResponse,boolean ambiguityRetryAllowed){this.sequence=sequence;
this.signature=signature;
this.targets=targets;
this.expectsTransportResponse=expectsTransportResponse;
this.ambiguityRetryAllowed=ambiguityRetryAllowed;
}Set<WorldPoint>getTargetsForTest(){return targets;
}}private static final class RequestSignature{private final WorldPoint start;
private final Set<WorldPoint>targets;
private final Map<String,Object>config;
private RequestSignature(WorldPoint start,Set<WorldPoint>targets,Map<String,Object>config){this.start=start;
this.targets=targets;
this.config=config;
}@Override public boolean equals(Object value){if(this==value){return true;
}if(!(value instanceof RequestSignature)){return false;
}RequestSignature other=(RequestSignature)value;
return Objects.equals(start,other.start)&&targets.equals(other.targets)&&config.equals(other.config);
}@Override public int hashCode(){return Objects.hash(start,targets,config);
}private boolean hasSameEndpoints(RequestSignature other){return other!=null&&Objects.equals(start,other.start)&&targets.equals(other.targets);
}private Map<String,Object>toMessageData(){Map<String,Object>data=new HashMap<>();
if(start!=null){data.put("start",start);
}data.put("target",targets);
data.put("config",config);
return data;
}}private static final class TransportResponse{private final List<WorldPoint>origins;
private final List<WorldPoint>destinations;
private TransportResponse(List<WorldPoint>origins,List<WorldPoint>destinations){this.origins=origins;
this.destinations=destinations;
}private boolean isEmpty(){return origins.isEmpty();
}}@Setter@Accessors(chain=true,fluent=true)private static final class PathOptions{private final boolean avoidWildy;
private boolean useBank;
private boolean bankPath;
private Integer distance;
private boolean waterTransports=true;
private boolean localOnly;
private boolean postTransportUpdates;
private boolean allowPoh=true;
private boolean showBankPickupInfo;
private boolean showTransportOverlay=true;
private boolean suppressReusable;
private boolean useAgilityShortcuts=true;
private PathOptions(boolean avoidWildy){this.avoidWildy=avoidWildy;
}}public ShortestPathBridge(EventBus eventBus){this.eventBus=eventBus;
}public boolean routeToTrackedInventory(WorldPoint destination,boolean avoidWildy){if(destination==null){return false;
}return postPath(null,destination,new PathOptions(avoidWildy).postTransportUpdates(true));
}public boolean routeToAny(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath){if(destinations==null||destinations.isEmpty()){return false;
}Set<WorldPoint>safeTargets=new LinkedHashSet<>();
for(WorldPoint destination:destinations){if(destination!=null){safeTargets.add(destination);
}}if(safeTargets.isEmpty()){return false;
}return postPath(start,safeTargets,new PathOptions(avoidWildy).useBank(useBank).bankPath(bankPath).postTransportUpdates(useBank));
}public boolean routeToPreparationAccess(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath){if(destinations==null||destinations.isEmpty()){return false;
}Set<WorldPoint>safeTargets=sanitizeTargets(destinations);
return!safeTargets.isEmpty()&&postPath(start,safeTargets,new PathOptions(avoidWildy).useBank(useBank).bankPath(bankPath).distance(PREPARATION_ACCESS_UNREACHABLE_DISTANCE).postTransportUpdates(useBank).allowPoh(false));
}public boolean routeToTaskArea(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath,boolean waterTransports,boolean suppressReusable){return routeToTaskArea(start,destinations,avoidWildy,useBank,bankPath,waterTransports,suppressReusable,true);
}public boolean routeToTaskArea(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath,boolean waterTransports,boolean suppressReusable,boolean showTransportOverlay){if(destinations==null||destinations.isEmpty()){return false;
}Set<WorldPoint>safeTargets=sanitizeTargets(destinations);
if(safeTargets.isEmpty()){return false;
}return postPath(start,safeTargets,new PathOptions(avoidWildy).useBank(useBank).bankPath(bankPath).distance(TASK_AREA_UNREACHABLE_DISTANCE).waterTransports(waterTransports).postTransportUpdates(true).suppressReusable(suppressReusable).showTransportOverlay(showTransportOverlay));
}public boolean routeToSpellbookChange(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean suppressReusable){Set<WorldPoint>safeTargets=sanitizeTargets(destinations);
return!safeTargets.isEmpty()&&postPath(start,safeTargets,new PathOptions(avoidWildy).useBank(true).bankPath(true).distance(TASK_AREA_UNREACHABLE_DISTANCE).showBankPickupInfo(true).postTransportUpdates(true).suppressReusable(suppressReusable));
}public boolean routeLocal(WorldPoint start,WorldPoint destination,boolean avoidWildy){if(destination==null){return false;
}return postPath(start,destination,new PathOptions(avoidWildy).distance(0).waterTransports(false).localOnly(true));
}public boolean routeToLocalBankTarget(WorldPoint start,WorldPoint destination,boolean avoidWildy){if(destination==null){return false;
}return postPath(start,destination,new PathOptions(avoidWildy).distance(PREPARATION_BANK_UNREACHABLE_DISTANCE).waterTransports(false).localOnly(true));
}public boolean routeToLocalTaskArea(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useAgilityShortcuts){if(destinations==null||destinations.isEmpty()){return false;
}Set<WorldPoint>safeTargets=sanitizeTargets(destinations);
return!safeTargets.isEmpty()&&postPath(start,safeTargets,new PathOptions(avoidWildy).distance(LOCAL_TASK_UNREACHABLE_DISTANCE).waterTransports(false).localOnly(true).useAgilityShortcuts(useAgilityShortcuts));
}private static Set<WorldPoint>sanitizeTargets(Set<WorldPoint>destinations){Set<WorldPoint>targets=new LinkedHashSet<>();
for(WorldPoint destination:destinations){if(destination!=null){targets.add(destination);
}}return targets;
}public boolean routeToTaskAccess(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath,boolean waterTransports){return routeToTaskAccess(start,destinations,avoidWildy,useBank,bankPath,waterTransports,true);
}public boolean routeToTaskAccess(WorldPoint start,Set<WorldPoint>destinations,boolean avoidWildy,boolean useBank,boolean bankPath,boolean waterTransports,boolean showTransportOverlay){if(destinations==null||destinations.isEmpty()){return false;
}Set<WorldPoint>safeTargets=sanitizeTargets(destinations);
return!safeTargets.isEmpty()&&postPath(start,safeTargets,new PathOptions(avoidWildy).useBank(useBank).bankPath(bankPath).distance(TASK_AREA_UNREACHABLE_DISTANCE).waterTransports(waterTransports).postTransportUpdates(true).showTransportOverlay(showTransportOverlay));
}private boolean postPath(WorldPoint start,Object target,PathOptions options){if(eventBus==null||target==null){return false;
}boolean avoidWildy=options.avoidWildy;
boolean useBank=options.useBank;
boolean bankPath=options.bankPath;
Integer distance=options.distance;
boolean waterTransports=options.waterTransports;
boolean localOnly=options.localOnly;
boolean postTransportUpdates=options.postTransportUpdates;
boolean allowPoh=options.allowPoh;
boolean showBankPickupInfo=options.showBankPickupInfo;
boolean showTransportOverlay=options.showTransportOverlay;
boolean suppressReusable=options.suppressReusable;
boolean useAgilityShortcuts=options.useAgilityShortcuts;
boolean bankAwarePath=useBank||bankPath;
Map<String,Object>overrides=new HashMap<>();
overrides.put("avoidWilderness",avoidWildy);
overrides.put(text(205),useAgilityShortcuts);
overrides.put(text(206),0);
overrides.put("drawMap",localOnly||showTransportOverlay);
if(localOnly){
overrides.put(text(207),false);
overrides.put("postTransports",false);
overrides.put(text(208),"None");
overrides.put(text(209),false);
overrides.put(text(210),false);
overrides.put(text(211),false);
overrides.put(text(212),false);
overrides.put(text(213),false);
overrides.put("usePoh",false);
}else if(!allowPoh){overrides.put("usePoh",false);
overrides.put(text(214),false);
overrides.put(text(215),false);
overrides.put(text(216),false);
overrides.put(text(217),false);
overrides.put(text(218),false);
overrides.put(text(219),"None");
}overrides.put("includeBankPath",bankAwarePath);
if(localOnly){overrides.put("showTransportInfo",false);
overrides.put(text(207),false);
overrides.put("postTransports",false);
}else{overrides.put("showTransportInfo",showTransportOverlay);
overrides.put(text(207),false);
overrides.put("postTransports",shouldPostTransportUpdates(useBank,postTransportUpdates,localOnly));
}if(!waterTransports){overrides.put("useBoats",false);
overrides.put("useShips",false);
overrides.put(text(220),false);
overrides.put("useCanoes",false);
}if(suppressReusable){overrides.put(text(221),1_000_000);
}if(!localOnly){overrides.put(text(208),useBank?BANK_AND_INVENTORY_TELEPORTS:INVENTORY_TELEPORTS);
}if(distance!=null){overrides.put(text(222),distance);
}Map<String,Object>data=new HashMap<>();
if(start!=null){data.put("start",start);
}data.put("target",target);
data.put("config",overrides);
Set<WorldPoint>requestTargets=canonicalTargets(target);
if(requestTargets.isEmpty()){return false;
}Map<String,Object>requestConfig=Collections.unmodifiableMap(new HashMap<>(overrides));
RequestSignature signature=new RequestSignature(start,requestTargets,requestConfig);
boolean expectsTransportResponse=Boolean.TRUE.equals(overrides.get("postTransports"));
RequestToken nextRequest;
synchronized(requestLock){if(activeRequest!=null&&activeRequest.signature.equals(signature)){return true;
}RequestToken previousRequest=activeRequest;
boolean supersedesExistingRequest=previousRequest!=null;
boolean canReceiveRetiredResponse=supersedesExistingRequest&&previousRequest.expectsTransportResponse&&acceptedRequestSequence!=previousRequest.sequence;
if(canReceiveRetiredResponse){rememberRetiredRequest(previousRequest.signature);
}activeRequest=null;
reservedRequestSequence=-1L;
if(supersedesExistingRequest){try{eventBus.post(new PluginMessage(NAMESPACE,CLEAR_MESSAGE));
}catch(RuntimeException ex){return false;
}}nextRequest=new RequestToken(++nextRequestSequence,signature,requestTargets,expectsTransportResponse,canReceiveRetiredResponse&&expectsTransportResponse);
activeRequest=nextRequest;
reservedRequestSequence=-1L;
try{eventBus.post(new PluginMessage(NAMESPACE,PATH_MESSAGE,data));
}catch(RuntimeException ex){if(activeRequest==nextRequest){activeRequest=null;
reservedRequestSequence=-1L;
}return false;
}}return true;
}private void rememberRetiredRequest(RequestSignature signature){if(signature==null){return;
}retiredRequests.remove(signature);
retiredRequests.addFirst(signature);
while(retiredRequests.size()>MAX_RETIRED_REQUESTS){retiredRequests.removeLast();
}}private static Set<WorldPoint>canonicalTargets(Object target){Set<WorldPoint>targets=new LinkedHashSet<>();
if(target instanceof WorldPoint){targets.add((WorldPoint)target);
}else if(target instanceof Iterable<?>){for(Object value:(Iterable<?>)target){if(value instanceof WorldPoint){targets.add((WorldPoint)value);
}}}else if(target instanceof Object[]){for(Object value:(Object[])target){if(value instanceof WorldPoint){targets.add((WorldPoint)value);
}}}return Collections.unmodifiableSet(targets);
}RequestToken currentPendingTransportRequest(){synchronized(requestLock){RequestToken request=activeRequest;
return isPendingTransportRequest(request)?request:null;
}}RequestToken claimPendingTransportResponse(){synchronized(requestLock){RequestToken request=activeRequest;
if(!isPendingTransportRequest(request)){return null;
}reservedRequestSequence=request.sequence;
return request;
}}void releaseTransportResponseClaim(RequestToken request){synchronized(requestLock){if(isActiveTransportRequest(request)&&reservedRequestSequence==request.sequence&&acceptedRequestSequence!=request.sequence){reservedRequestSequence=-1L;
}}}private boolean isPendingTransportRequest(RequestToken request){return isActiveTransportRequest(request)&&request.expectsTransportResponse&&acceptedRequestSequence!=request.sequence&&reservedRequestSequence!=request.sequence;
}private boolean isActiveTransportRequest(RequestToken request){return request!=null&&activeRequest!=null&&activeRequest.sequence==request.sequence&&activeRequest.signature.equals(request.signature)&&activeRequest.targets.equals(request.targets);
}boolean tryAcceptTransportResponse(RequestToken request,Map<String,Object>data){if(request==null||!request.expectsTransportResponse){return false;
}synchronized(requestLock){if(!isActiveTransportRequest(request)||acceptedRequestSequence==request.sequence||reservedRequestSequence!=request.sequence){return false;
}}TransportResponse response=parseTransportResponse(data);
if(response==null){releaseTransportResponseClaim(request);
return false;
}List<RequestSignature>retiredSnapshot;
synchronized(requestLock){if(!isActiveTransportRequest(request)||acceptedRequestSequence==request.sequence||reservedRequestSequence!=request.sequence){return false;
}retiredSnapshot=new ArrayList<>(retiredRequests);
}if(request.ambiguityRetryAllowed&&responseNeedsBarrierRetry(request.signature,response,retiredSnapshot)){retryAmbiguousTransportRequest(request);
return false;
}if(!response.isEmpty()&&distanceToNearestTarget(response.destinations.get(response.destinations.size()-1),request.targets)>MAX_RELEVANT_EDGE_DISTANCE){releaseTransportResponseClaim(request);
return false;
}synchronized(requestLock){if(!isActiveTransportRequest(request)||acceptedRequestSequence==request.sequence||reservedRequestSequence!=request.sequence){return false;
}acceptedRequestSequence=request.sequence;
reservedRequestSequence=-1L;
retiredRequests.clear();
return true;
}}private boolean retryAmbiguousTransportRequest(RequestToken request){synchronized(requestLock){if(!isActiveTransportRequest(request)||!request.ambiguityRetryAllowed||acceptedRequestSequence==request.sequence||reservedRequestSequence!=request.sequence){return false;
}activeRequest=null;
reservedRequestSequence=-1L;
try{eventBus.post(new PluginMessage(NAMESPACE,CLEAR_MESSAGE));
}catch(RuntimeException ex){return false;
}RequestToken replacement=new RequestToken(++nextRequestSequence,request.signature,request.targets,request.expectsTransportResponse,false);
activeRequest=replacement;
try{eventBus.post(new PluginMessage(NAMESPACE,PATH_MESSAGE,request.signature.toMessageData()));
return true;
}catch(RuntimeException ex){if(activeRequest==replacement){activeRequest=null;
reservedRequestSequence=-1L;
}return false;
}}}private static boolean responseNeedsBarrierRetry(RequestSignature current,TransportResponse response,List<RequestSignature>retired){if(current==null||retired==null||retired.isEmpty()){return false;
}if(response.isEmpty()){return true;
}long bestRetiredAffinity=Long.MAX_VALUE;
for(RequestSignature previous:retired){if(current.hasSameEndpoints(previous)){return true;
}bestRetiredAffinity=Math.min(bestRetiredAffinity,endpointAffinity(previous,response));
}if(bestRetiredAffinity==Long.MAX_VALUE){return false;
}long currentAffinity=endpointAffinity(current,response);
return currentAffinity==Long.MAX_VALUE||currentAffinity+ENDPOINT_AFFINITY_MARGIN>=bestRetiredAffinity;
}private static long endpointAffinity(RequestSignature signature,TransportResponse response){if(signature==null||response==null||response.isEmpty()){return Long.MAX_VALUE;
}long targetDistance=distanceToNearestTarget(response.destinations.get(response.destinations.size()-1),signature.targets);
if(targetDistance==Long.MAX_VALUE){return Long.MAX_VALUE;
}long affinity=targetDistance;
if(signature.start!=null){WorldPoint firstOrigin=response.origins.get(0);
if(signature.start.getPlane()==firstOrigin.getPlane()){affinity+=chebyshevDistance(signature.start,firstOrigin);
}}return affinity;
}private static long distanceToNearestTarget(WorldPoint point,Set<WorldPoint>targets){if(point==null||targets==null||targets.isEmpty()){return Long.MAX_VALUE;
}long closest=Long.MAX_VALUE;
for(WorldPoint target:targets){if(target!=null&&point.getPlane()==target.getPlane()){closest=Math.min(closest,chebyshevDistance(point,target));
}}return closest;
}private static long chebyshevDistance(WorldPoint first,WorldPoint second){return Math.max(Math.abs((long)first.getX()-second.getX()),Math.abs((long)first.getY()-second.getY()));
}private static TransportResponse parseTransportResponse(Map<String,Object>data){if(data==null||!data.containsKey("origin")||!data.containsKey("destination")||!data.containsKey("objectInfo")||!data.containsKey("displayInfo")){return null;
}List<?>originValues=responseValues(data.get("origin"));
List<?>destinationValues=responseValues(data.get("destination"));
List<?>objectInfos=responseValues(data.get("objectInfo"));
List<?>displayInfos=responseValues(data.get("displayInfo"));
if(originValues==null||destinationValues==null||objectInfos==null||displayInfos==null||originValues.size()!=destinationValues.size()||originValues.size()!=objectInfos.size()||originValues.size()!=displayInfos.size()){return null;
}List<WorldPoint>origins=new ArrayList<>(originValues.size());
List<WorldPoint>destinations=new ArrayList<>(destinationValues.size());
for(int index=0;
index<originValues.size();
index++){Object origin=originValues.get(index);
Object destination=destinationValues.get(index);
Object objectInfo=objectInfos.get(index);
Object displayInfo=displayInfos.get(index);
if(!(origin instanceof WorldPoint)||!(destination instanceof WorldPoint)||(objectInfo!=null&&!(objectInfo instanceof String))||(displayInfo!=null&&!(displayInfo instanceof String))){return null;
}origins.add((WorldPoint)origin);
destinations.add((WorldPoint)destination);
}return new TransportResponse(origins,destinations);
}private static List<?>responseValues(Object value){if(value instanceof List<?>){return(List<?>)value;
}if(value instanceof Object[]){return new ArrayList<>(java.util.Arrays.asList((Object[])value));
}return null;
}static boolean shouldPostTransportUpdates(boolean useBank,boolean explicitlyTrackInventoryRoute,boolean localOnly){return!localOnly&&explicitlyTrackInventoryRoute;
}public void clear(){synchronized(requestLock){activeRequest=null;
acceptedRequestSequence=-1L;
reservedRequestSequence=-1L;
retiredRequests.clear();
++nextRequestSequence;
}if(eventBus!=null){eventBus.post(new PluginMessage(NAMESPACE,CLEAR_MESSAGE));
}}static int preparationBankApproachThresholdForTest(){return PREPARATION_BANK_UNREACHABLE_DISTANCE;
}static int preparationAccessApproachThresholdForTest(){return PREPARATION_ACCESS_UNREACHABLE_DISTANCE;
}static boolean showsNativeTransportInfoForTest(boolean useBank,boolean bankPath){return true;
}}
