package com.slayerplus;
import java.util.*;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
public final class SlayerRouteCoordinator{public enum StageKind{SURFACE_APPROACH,EXACT_ENTRANCE,METHOD_POSITION,EXACT_NPC,LEARNED_CHECKPOINT,INTERIOR,ACCESS,WAIT_FOR_NPC}@Getter public static final class Stage{private final StageKind kind;
private final WorldPoint destination;
private final Set<WorldPoint>targets;
private Stage(StageKind kind,WorldPoint destination,Set<WorldPoint>targets){this.kind=kind;
this.destination=destination;
this.targets=targets==null||targets.isEmpty()?Collections.emptySet():Collections.unmodifiableSet(new LinkedHashSet<>(targets));
}public boolean isValid(){return kind!=StageKind.WAIT_FOR_NPC&&destination!=null&&!targets.isEmpty();
}}private SlayerRouteCoordinator(){}public static Stage resolve(RouteCatalog.RouteProfile profile,WorldPoint here,WorldPoint exactEntrance,Set<WorldPoint>exactEntranceTargets,WorldPoint methodPosition,Set<WorldPoint>methodTargets,WorldPoint exactNpc,Set<WorldPoint>exactNpcTargets,WorldPoint learnedCheckpoint,Set<WorldPoint>learnedTargets){if(profile==null){return new Stage(StageKind.WAIT_FOR_NPC,null,Collections.emptySet());
}if(profile.shouldRouteToSurfaceAccess(here)){if(exactEntrance!=null&&exactEntranceTargets!=null&&!exactEntranceTargets.isEmpty()){return new Stage(StageKind.EXACT_ENTRANCE,exactEntrance,exactEntranceTargets);
}WorldPoint access=profile.getSurfaceAccess();
return new Stage(StageKind.SURFACE_APPROACH,access,access==null?Collections.emptySet():profile.getRouteTargets(here));
}if(methodPosition!=null&&methodTargets!=null&&!methodTargets.isEmpty()){return new Stage(StageKind.METHOD_POSITION,methodPosition,methodTargets);
}if(exactNpc!=null&&exactNpcTargets!=null&&!exactNpcTargets.isEmpty()){return new Stage(StageKind.EXACT_NPC,exactNpc,exactNpcTargets);
}if(learnedCheckpoint!=null&&learnedTargets!=null&&!learnedTargets.isEmpty()){return new Stage(StageKind.LEARNED_CHECKPOINT,learnedCheckpoint,learnedTargets);
}if(profile.requiresLoadedNpc()){return new Stage(StageKind.WAIT_FOR_NPC,null,Collections.emptySet());
}if(profile.isAccessThenNpc()){WorldPoint access=profile.getRouteDestination(here);
if(access==null||!sameCoordinateLayer(here,access)){return new Stage(StageKind.WAIT_FOR_NPC,null,Collections.emptySet());
}return new Stage(StageKind.ACCESS,access,profile.getRouteTargets(here));
}WorldPoint destination=profile.getRouteDestination(here);
return new Stage(StageKind.INTERIOR,destination,profile.getRouteTargets(here));
}private static boolean sameCoordinateLayer(WorldPoint first,WorldPoint second){if(first==null||second==null){return true;
}return first.getPlane()==second.getPlane()&&(first.getY()>>>12)==(second.getY()>>>12);
}}
