package com.slayerplus;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.image.BufferedImage;
import javax.inject.Inject;
import net.runelite.api.widgets.WidgetItem;
import net.runelite.client.game.ItemManager;
import net.runelite.client.ui.overlay.WidgetItemOverlay;
class SlayerTravelItemOverlay extends WidgetItemOverlay{private static final Color TRAVEL_ITEM_COLOR=new Color(0,255,80);
private final ItemManager itemManager;
private final SlayerPlusPlugin plugin;
private int cachedItemId=-1;
private int cachedQuantity=-1;
private BufferedImage cachedOutline;
@Inject private SlayerTravelItemOverlay(ItemManager itemManager,SlayerPlusPlugin plugin){this.itemManager=itemManager;
this.plugin=plugin;
showOnInventory();
}@Override public Dimension render(Graphics2D graphics){return plugin.getTravelItemIdForOverlay()>0?super.render(graphics):null;
}@Override public void renderItemOverlay(Graphics2D graphics,int itemId,WidgetItem widgetItem){if(graphics==null||widgetItem==null||itemId!=plugin.getTravelItemIdForOverlay()){return;
}Rectangle bounds=widgetItem.getCanvasBounds();
if(bounds==null){return;
}int quantity=widgetItem.getQuantity();
if(cachedOutline==null||cachedItemId!=itemId||cachedQuantity!=quantity){cachedItemId=itemId;
cachedQuantity=quantity;
cachedOutline=itemManager.getItemOutline(itemId,quantity,TRAVEL_ITEM_COLOR);
}graphics.drawImage(cachedOutline,bounds.x,bounds.y,null);
}}
