package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.List;
public final class SlayerEncounterStandards{private SlayerEncounterStandards(){}public static String cleanEncounterLabel(String value){if(value==null||value.trim().isEmpty()){return "Task";
}return value.trim().replaceFirst("(?i)^regular\\s+","").replaceFirst("(?i)\\s*\\((?:boss|bosses)\\)\\s*$","").replaceFirst("(?i)\\s*\\[(?:boss|bosses)\\]\\s*$","").replaceFirst("(?i)\\s*[-–—]\\s*(?:boss|bosses)\\s*$","").trim();
}public static String resolveTaskMethod(String encounter,String location,boolean bossEncounter,String routePositioningNote,TaskStrategy strategy){if(strategy!=null&&strategy.isReviewed()){MethodRules rules=SlayerMethodRuleCatalog.resolve(encounter,location,strategy);
String method=safe(rules.getMethod());
if(!method.isEmpty()){return method;
}}String authored=strategy==null?"":safe(strategy.getMethod());
if(!authored.isEmpty()){return authored;
}String route=safe(routePositioningNote);
return route.isEmpty()?text(253):route;
}public static String resolveTaskMethod(String encounter,boolean bossEncounter,String routePositioningNote,TaskStrategy strategy){return resolveTaskMethod(encounter,"",bossEncounter,routePositioningNote,strategy);
}public static boolean validateBossDefinitions(List<VariantCatalog.EncounterDefinition>definitions){if(definitions==null){throw new IllegalStateException(text(254));
}for(VariantCatalog.EncounterDefinition definition:definitions){if(definition==null){throw new IllegalStateException(text(255));
}if(definition.getVariant()!=null&&!definition.getVariant().isBoss()){throw new IllegalStateException(text(256)+definition.getTargetName());
}if(safe(definition.getTargetName()).isEmpty()){throw new IllegalStateException(text(257));
}if(safe(definition.getLocation()).isEmpty()){throw new IllegalStateException(text(258)+definition.getTargetName());
}if(cleanEncounterLabel(definition.getOptionLabel()).equals("Task")){throw new IllegalStateException(text(259)+definition.getTargetName());
}}return true;
}private static String safe(String value){return value==null?"":value.trim();
}}
