package com.slayerplus;
import net.runelite.client.config.*;
@ConfigGroup(SlayerPlusConfig.GROUP)public interface SlayerPlusConfig extends Config{String GROUP="slayerplus";
@ConfigSection(name="Slayer workflow",description="Controls normal Slayer sessions or guided Turael point boosting.",position=0)String WORKFLOW_SECTION="workflow";
@ConfigSection(name="Recommendation preferences",description="Controls how SlayerPlus ranks valid task locations.",position=1)String RECOMMENDATION_SECTION="recommendation";
@ConfigSection(name="Loadout scanning",description="Controls equipment, inventory, and bank recommendations.",position=2)String LOADOUT_SECTION="loadout";
@ConfigItem(keyName="slayerWorkflow",name="Slayer workflow",description="Normal Slayer follows the assigning master. Turael point boosting uses nine Turael or"+" Aya tasks followed by each tenth task from the selected bonus master.",position=0,section=WORKFLOW_SECTION)default Preference.Workflow slayerWorkflow(){return Preference.Workflow.NORMAL;
}@ConfigItem(keyName="pointBoostBonusMaster",name="Bonus-task master",description="The Slayer master used for every tenth point-boosting task.",position=1,section=WORKFLOW_SECTION)default Preference.BonusMaster pointBoostBonusMaster(){return Preference.BonusMaster.KONAR;
}@ConfigItem(keyName="combatStylePreference",name="Combat style",description="Automatic uses the best individually researched method. A preferred style is used only"+" when the task has a verified viable setup for it.",position=0,section=RECOMMENDATION_SECTION)default Preference.CombatStyle combatStylePreference(){return Preference.CombatStyle.AUTOMATIC;
}@ConfigItem(keyName="playstyle",name="Playstyle",description="Fast XP prioritizes maximum damage without considering gear or charge cost. Profit"+" favors efficient supplies and loot.",position=1,section=RECOMMENDATION_SECTION)default Preference.Playstyle playstyle(){return Preference.Playstyle.FAST_XP;
}@ConfigItem(keyName="cannonPreference",name="Cannon",description="Prefer, allow, or avoid cannon locations.",position=2,section=RECOMMENDATION_SECTION)default Preference.Cannon cannonPreference(){return Preference.Cannon.ALLOW;
}@ConfigItem(keyName="burstPreference",name="Burst / barrage",description="Prefer, allow, or avoid burst and barrage methods.",position=3,section=RECOMMENDATION_SECTION)default Preference.Burst burstPreference(){return Preference.Burst.ALLOW;
}@ConfigItem(keyName="travelPreference",name="Travel",description="Choose how travel routes affect location scoring.",position=4,section=RECOMMENDATION_SECTION)default Preference.Travel travelPreference(){return Preference.Travel.FASTEST;
}@ConfigItem(keyName="shardPreference",name="Shard preference",description="Prefer valid task locations that drop ancient shards, crystal shards, both, or neither."+" Assigned-area and Wilderness restrictions always take priority.",position=5,section=RECOMMENDATION_SECTION)default Preference.Shard shardPreference(){return Preference.Shard.NO_PREFERENCE;
}@ConfigItem(keyName="showLoadoutRecommendations",name="Show loadout recommendations",description="Scan worn, inventory, and cached bank items for the current task.",position=0,section=LOADOUT_SECTION)default boolean showLoadoutRecommendations(){return true;
}}
