package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
public final class SlayerTaskNpcCatalog{private static final CatalogData DATA=loadCatalog();
private static final Map<String,Set<String>>ALIASES=DATA.aliases;
private static final Map<String,Set<String>>STANDARD_EXCLUSIONS=DATA.exclusions;
static{validateOrThrow();
}private SlayerTaskNpcCatalog(){}public static Set<String>aliasesFor(String assignment){Set<String>aliases=new LinkedHashSet<>();
addAlias(aliases,assignment);
addAlias(aliases,singular(normalize(assignment)));
Set<String>reviewed=ALIASES.get(taskKey(assignment));
if(reviewed!=null){aliases.addAll(reviewed);
}return aliases;
}public static Set<String>aliasesForStandardRoute(String assignment){Set<String>aliases=new LinkedHashSet<>(aliasesFor(assignment));
Set<String>excluded=STANDARD_EXCLUSIONS.get(taskKey(assignment));
if(excluded!=null){aliases.removeAll(excluded);
}return aliases;
}public static void validateOrThrow(){for(Map.Entry<String,Set<String>>entry:ALIASES.entrySet()){if(entry.getKey()==null||entry.getKey().trim().isEmpty()||entry.getValue()==null||entry.getValue().isEmpty()){throw new IllegalStateException(text(951)+entry.getKey());
}for(String alias:entry.getValue()){if(alias==null||alias.trim().isEmpty()){throw new IllegalStateException(text(952)+entry.getKey());
}}}for(Map.Entry<String,Set<String>>entry:STANDARD_EXCLUSIONS.entrySet()){Set<String>base=aliasesFor(entry.getKey());
Set<String>standard=aliasesForStandardRoute(entry.getKey());
for(String excluded:entry.getValue()){if(!base.contains(excluded)){throw new IllegalStateException(text(953)+entry.getKey()+" -> "+excluded);
}if(standard.contains(excluded)){throw new IllegalStateException(text(954)+entry.getKey()+" -> "+excluded);
}}}}private static CatalogData loadCatalog(){Map<String,Set<String>>aliases=new LinkedHashMap<>();
Map<String,Set<String>>exclusions=new LinkedHashMap<>();
for(String[]fields:ResourceTable.decodedRows(text(955),3)){if(!fields[0].equals("A")&&!fields[0].equals("X")){throw new IllegalStateException(text(956)+fields[0]);
}String[]names=fields[2].split("\\|",-1);
if(fields[0].equals("A")){put(aliases,fields[1],names);
}else{putExclusions(exclusions,fields[1],names);
}}return new CatalogData(Collections.unmodifiableMap(aliases),Collections.unmodifiableMap(exclusions));
}private static void putExclusions(Map<String,Set<String>>map,String assignment,String...npcNames){Set<String>excluded=new LinkedHashSet<>();
if(npcNames!=null){for(String npcName:npcNames){addAlias(excluded,npcName);
}}String key=taskKey(assignment);
Set<String>immutable=Collections.unmodifiableSet(excluded);
Set<String>previous=map.put(key,immutable);
if(previous!=null&&!previous.equals(immutable)){throw new IllegalStateException(text(957)+assignment);
}}private static void put(Map<String,Set<String>>map,String assignment,String...npcNames){Set<String>aliases=new LinkedHashSet<>();
if(npcNames!=null){for(String npcName:npcNames){addAlias(aliases,npcName);
}}String key=taskKey(assignment);
Set<String>immutable=Collections.unmodifiableSet(aliases);
Set<String>previous=map.put(key,immutable);
if(previous!=null&&!previous.equals(immutable)){throw new IllegalStateException(text(958)+assignment);
}}private static void addAlias(Set<String>aliases,String value){String normalized=normalize(value);
if(!normalized.isEmpty()){aliases.add(normalized);
aliases.add(singular(normalized));
}}private static String taskKey(String value){String normalized=singular(normalize(value));
if(normalized.startsWith("the ")){normalized=normalized.substring(4);
}return normalized;
}private static String normalize(String value){if(value==null){return "";
}return value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim().replaceAll("\\s+"," ");
}private static String singular(String value){if(value==null||value.isEmpty()){return "";
}if(value.endsWith("wolves")){return value.substring(0,value.length()-6)+"wolf";
}if(value.endsWith("elves")){return value.substring(0,value.length()-5)+"elf";
}if(value.endsWith("dwarves")){return value.substring(0,value.length()-7)+"dwarf";
}if(value.endsWith("men")){return value.substring(0,value.length()-3)+"man";
}if(value.endsWith("ies")&&value.length()>4){return value.substring(0,value.length()-3)+"y";
}if(value.endsWith("s")&&!value.endsWith("ss")&&!value.endsWith("us")&&!value.endsWith("is")&&value.length()>3){return value.substring(0,value.length()-1);
}return value;
}private static final class CatalogData{private final Map<String,Set<String>>aliases;
private final Map<String,Set<String>>exclusions;
private CatalogData(Map<String,Set<String>>aliases,Map<String,Set<String>>exclusions){this.aliases=aliases;
this.exclusions=exclusions;
}}}
