package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
import net.runelite.api.EquipmentInventorySlot;
public final class SlayerEquipmentAuditCatalog{private static final Map<String,List<String>>LISTS=loadLists();
private static final Map<String,Map<EquipmentInventorySlot,List<String>>>PROFILES=loadProfiles();
private SlayerEquipmentAuditCatalog(){}public static List<String>priorities(String assignment,TaskStrategy strategy,EquipmentInventorySlot slot,String selectedWeaponName){if(strategy==null||slot==null){return Collections.emptyList();
}var style=strategy.getStyle();
var focus=strategy.getArmourFocus();
var task=normalize(assignment);
var weapon=normalize(selectedWeaponName);
var prayer=focus==TaskStrategy.ArmourFocus.PRAYER;
var magicDefence=focus==TaskStrategy.ArmourFocus.MAGIC_DEFENCE;
var wilderness=strategy.getCostPolicy()==TaskStrategy.CostPolicy.LOW_RISK||strategy.hasTag(TaskStrategy.MethodTag.WILDERNESS);
if(slot==EquipmentInventorySlot.HEAD){if(task.contains(text(260))){return list("e039");
}if((task.equals("blue dragon")||task.equals("blue dragons"))&&style==TaskStrategy.CombatStyle.RANGED){return list("e040");
}return style==TaskStrategy.CombatStyle.MELEE?list("e041"):list("e042");
}if(task.equals("blue dragon")||task.equals("blue dragons")){return profile(style==TaskStrategy.CombatStyle.MAGIC?"blue-magic":style==TaskStrategy.CombatStyle.MELEE?"blue-melee":"blue-ranged",slot);
}if(task.equals("vorkath")){return profile(style==TaskStrategy.CombatStyle.MELEE?text(261):text(262),slot);
}if(task.equals(text(2))){return ranged(slot,weapon,false);
}if(task.equals(text(263))){return royalTitans(slot);
}if(task.equals("araxxor")){return araxxor(slot,weapon);
}if(task.equals("dagannoth rex")){return profile("dagannoth-rex",slot);
}if(task.equals("dagannoth kings")){return profile("dagannoth-kings",slot);
}if(slot==EquipmentInventorySlot.AMULET&&task.contains("banshee")){return list("e043");
}if((task.equals("blue dragon")||task.equals("blue dragons"))&&style==TaskStrategy.CombatStyle.RANGED&&slot==EquipmentInventorySlot.SHIELD){return list("e044");
}if((task.equals("skeletal wyvern")||task.equals(text(264)))&&slot==EquipmentInventorySlot.SHIELD){if(style==TaskStrategy.CombatStyle.RANGED){return list("e045");
}if(style==TaskStrategy.CombatStyle.MAGIC){return list("e046");
}return list("e047");
}if(task.equals("barrows brothers")){return slot==EquipmentInventorySlot.HEAD?list("e048"):profile("barrows",slot);
}if(task.equals(text(231))&&style==TaskStrategy.CombatStyle.RANGED){if(weapon.contains(text(265))){if(slot==EquipmentInventorySlot.BODY){return list("e053");
}if(slot==EquipmentInventorySlot.LEGS){return list("e055");
}}return profile(text(266),slot);
}if(task.equals(text(231))&&style==TaskStrategy.CombatStyle.MELEE){return profile(text(267),slot);
}if(task.equals(text(268))||task.equals(text(269))){return profile("grotesque",slot);
}if(task.equals("tormented demons")){return profile("tormented",slot);
}if(task.equals("whisperer")||task.equals("the whisperer")){if(slot==EquipmentInventorySlot.RING&&weapon.contains(text(270))){return list("e086");
}return profile("whisperer",slot);
}if(task.equals("kalphite queen")||task.equals(text(271))){return profile(style==TaskStrategy.CombatStyle.MAGIC?text(272):text(273),slot);
}if(task.contains(text(260))){switch(slot){case BODY:return list("e100");
case LEGS:return list("e101");
case SHIELD:return list("e102");
case BOOTS:return list("e103");
default:break;
}}if(task.equals("gryphon")||task.equals("gryphons")){switch(slot){case HEAD:return list("e039");
case BODY:return list("e104");
case LEGS:return list("e105");
case BOOTS:return list("e106");
default:break;
}}if(task.contains(text(274))){return profile("maggot",slot);
}if(wilderness){return wilderness(style,slot);
}if(slot==EquipmentInventorySlot.GLOVES&&strategy.isBoss()){return bossGloves(style);
}switch(style){case RANGED:return ranged(slot,weapon,prayer);
case MAGIC:return magic(slot,prayer,magicDefence,assignment);
case HYBRID:return hybrid(slot);
case MELEE:default:return melee(slot,prayer,magicDefence);
}}private static List<String>bossGloves(TaskStrategy.CombatStyle style){switch(style){case RANGED:return list("e110");
case MAGIC:return list("e111");
case HYBRID:return list("e112");
case MELEE:default:return list("e113");
}}public static List<String>weaponProgression(TaskStrategy strategy){if(strategy==null){return Collections.emptyList();
}var wilderness=strategy.getCostPolicy()==TaskStrategy.CostPolicy.LOW_RISK||strategy.hasTag(TaskStrategy.MethodTag.WILDERNESS);
if(wilderness){switch(strategy.getStyle()){case MAGIC:return list("e114");
case RANGED:return list("e115");
case MELEE:default:return list("e116");
}}switch(strategy.getStyle()){case RANGED:return list("e117");
case MAGIC:return list("e118");
case HYBRID:return list("e119");
case MELEE:default:return list("e120");
}}private static List<String>melee(EquipmentInventorySlot slot,boolean prayer,boolean magicDefence){var overlay=magicDefence?text(275):prayer?text(276):null;
var values=overlay==null?null:profile(overlay,slot);
if(values!=null&&!values.isEmpty()){return values;
}return profile("melee",slot);
}private static List<String>ranged(EquipmentInventorySlot slot,String weapon,boolean prayer){if(weapon.contains(text(265))){if(slot==EquipmentInventorySlot.BODY){return prepend("crystal body",profile("ranged",slot));
}if(slot==EquipmentInventorySlot.LEGS){return prepend("crystal legs",profile("ranged",slot));
}}var values=prayer?profile(text(277),slot):null;
if(values!=null&&!values.isEmpty()){return values;
}return profile("ranged",slot);
}private static List<String>magic(EquipmentInventorySlot slot,boolean prayer,boolean magicDefence,String assignment){var accuracySensitive=normalize(assignment).contains("smoke devil");
var overlay=magicDefence?"magic-defence":prayer&&!accuracySensitive?"magic-prayer":null;
var values=overlay==null?null:profile(overlay,slot);
if(values!=null&&!values.isEmpty()){return values;
}return profile("magic",slot);
}private static List<String>hybrid(EquipmentInventorySlot slot){return profile("hybrid",slot);
}private static List<String>royalTitans(EquipmentInventorySlot slot){return profile(text(278),slot);
}private static List<String>araxxor(EquipmentInventorySlot slot,String weapon){var soulreaper=weapon.contains(text(279));
if(soulreaper){if(slot==EquipmentInventorySlot.BODY){return list("e139");
}if(slot==EquipmentInventorySlot.LEGS){return list("e141");
}}return profile("araxxor",slot);
}private static List<String>wilderness(TaskStrategy.CombatStyle style,EquipmentInventorySlot slot){var name=style==TaskStrategy.CombatStyle.MAGIC?text(280):style==TaskStrategy.CombatStyle.MELEE?text(281):text(282);
return profile(name,slot);
}private static List<String>prepend(String value,List<String>remaining){var values=new String[remaining.size()+1];
values[0]=value;
for(var i=0;
i<remaining.size();
i++){values[i+1]=remaining.get(i);
}return values(values);
}private static List<String>values(String...values){return Collections.unmodifiableList(Arrays.asList(values));
}private static List<String>list(String key){var values=LISTS.get(key);
if(values==null){throw new IllegalStateException(text(283)+key);
}return values;
}private static List<String>profile(String name,EquipmentInventorySlot slot){var values=PROFILES.get(name);
if(values==null){throw new IllegalStateException(text(284)+name);
}return values.getOrDefault(slot,Collections.emptyList());
}private static Map<String,List<String>>loadLists(){Map<String,List<String>>lists=new LinkedHashMap<>();
for(String[]row:ResourceTable.rows(text(285),2)){lists.put(row[0],values(row[1].split("\\|",-1)));
}return Collections.unmodifiableMap(lists);
}private static Map<String,Map<EquipmentInventorySlot,List<String>>>loadProfiles(){EquipmentInventorySlot[]slots={EquipmentInventorySlot.CAPE,EquipmentInventorySlot.AMULET,EquipmentInventorySlot.BODY,EquipmentInventorySlot.SHIELD,EquipmentInventorySlot.LEGS,EquipmentInventorySlot.GLOVES,EquipmentInventorySlot.BOOTS,EquipmentInventorySlot.RING,EquipmentInventorySlot.AMMO};
Map<String,Map<EquipmentInventorySlot,List<String>>>profiles=new LinkedHashMap<>();
for(String[]row:ResourceTable.rows(text(286),10)){Map<EquipmentInventorySlot,List<String>>values=new EnumMap<>(EquipmentInventorySlot.class);
for(var i=0;
i<slots.length;
i++){if(!row[i+1].isEmpty()&&!row[i+1].equals("-")){values.put(slots[i],list(row[i+1]));
}}profiles.put(row[0],Collections.unmodifiableMap(values));
}return Collections.unmodifiableMap(profiles);
}private static String normalize(String value){return SlayerText.normalize(value);
}}
