package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
class SlayerTaskTravelAuditCatalog{static final class Entry{private final String location;
private final String travel;
private final String cannon;
private Entry(String location,String travel,String cannon){this.location=location;
this.travel=travel;
this.cannon=cannon;
}String getLocation(){return location;
}String getTravel(){return travel;
}String getCannon(){return cannon;
}}private static final Map<String,Entry>ENTRIES=loadEntries();
private SlayerTaskTravelAuditCatalog(){}static Entry find(String assignment){return ENTRIES.get(normalize(assignment));
}static int sizeForTest(){return ENTRIES.size();
}private static Map<String,Entry>loadEntries(){Map<String,Entry>entries=new LinkedHashMap<>();
for(String[]fields:ResourceTable.rows(text(1005),4)){entries.put(normalize(fields[0]),new Entry(fields[1],fields[2],fields[3]));
}return Collections.unmodifiableMap(entries);
}private static String normalize(String value){return value==null?"":value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim().replaceFirst("^the\\s+","");
}}
