package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.Set;
import lombok.Getter;
import net.runelite.api.coords.WorldPoint;
public final class SlayerSpellbookRouteCatalog{static final int STANDARD=0;
static final int ANCIENT=1;
static final int LUNAR=2;
static final int ARCEUUS=3;
private static final Route ANCIENT_ROUTE=new Route(text(101),new WorldPoint(3231,9311,0),text(941));
private static final Route LUNAR_ROUTE=new Route("Lunar spellbook",new WorldPoint(2156,3864,0),text(942));
private static final Route ARCEUUS_ROUTE=new Route(text(102),new WorldPoint(1714,3883,0),text(943)+" spellbook.");
private static final Route STANDARD_FROM_ARCEUUS_ROUTE=new Route("Standard spellbook",new WorldPoint(1714,3883,0),text(944)+" spellbook.");
private SlayerSpellbookRouteCatalog(){}public static Route resolve(String book,int currentSpellbook){String required=normalize(book);
if(required.contains("ancient")){return currentSpellbook==ANCIENT?null:ANCIENT_ROUTE;
}if(required.contains("lunar")){return currentSpellbook==LUNAR?null:LUNAR_ROUTE;
}if(required.contains("arceuus")){return currentSpellbook==ARCEUUS?null:ARCEUUS_ROUTE;
}if(required.contains("standard")){switch(currentSpellbook){case ANCIENT:return ANCIENT_ROUTE;
case LUNAR:return LUNAR_ROUTE;
case ARCEUUS:return STANDARD_FROM_ARCEUUS_ROUTE;
case STANDARD:default:return null;
}}return null;
}private static String normalize(String value){return value==null?"":value.trim().toLowerCase(java.util.Locale.ENGLISH);
}@Getter public static final class Route{private final String bookName;
private final WorldPoint destination;
private final String interaction;
private Route(String bookName,WorldPoint destination,String interaction){this.bookName=bookName;
this.destination=destination;
this.interaction=interaction;
}public Set<WorldPoint>getTargets(){return RouteCatalog.targetArea(destination,2);
}}}
