package com.slayerplus;
import static com.slayerplus.Text.text;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import net.runelite.api.*;
public final class SlayerRecommendationEngine{private static final int KRYSTILIA=7;
private static final int KONAR_MASTER_ID=8;
private static final Map<String,List<LocationOption>>TASK_LOCATIONS=createTaskLocations();
private final Client client;
private final SlayerPlusConfig config;
private final Map<String,List<LocationOption>>taskLocations;
public SlayerRecommendationEngine(Client client){this(client,null);
}public SlayerRecommendationEngine(Client client,SlayerPlusConfig config){this.client=client;
this.config=config;
this.taskLocations=TASK_LOCATIONS;
}static Set<String>catalogLocationsForValidation(String assignment){List<LocationOption>options=TASK_LOCATIONS.get(normalize(assignment));
if(options==null||options.isEmpty()){return Collections.emptySet();
}Set<String>locations=new LinkedHashSet<>();
for(LocationOption option:options){if(option!=null&&option.location!=null&&!option.location.trim().isEmpty()){locations.add(option.location.trim());
}}return Collections.unmodifiableSet(locations);
}public Recommendation recommend(String assignment,int masterId,String assignedLocation){String normalizedTask=normalize(assignment);
if(normalizedTask.isEmpty()){return genericRecommendation("Unknown task",masterId);
}if(masterId==KONAR_MASTER_ID||isAssignedArea(assignedLocation)){return assignedAreaRecommendation(normalizedTask,assignedLocation,masterId);
}if(masterId==KRYSTILIA){return wildernessRecommendation(assignment);
}if(masterId==BoostCoordinator.TURAEL_AYA_MASTER_ID&&config!=null&&config.slayerWorkflow()==Preference.Workflow.TURAEL_POINT_BOOST){Recommendation boost=turaelBoostRecommendation(assignment);
if(boost!=null){return boost;
}}List<LocationOption>options=taskLocations.get(normalizedTask);
if(options==null||options.isEmpty()){return genericRecommendation(assignment,masterId);
}LocationOption selected=null;
int selectedScore=Integer.MIN_VALUE;
LocationOption lockedUpgrade=null;
int lockedScore=Integer.MIN_VALUE;
for(LocationOption option:options){if(option.wilderness){continue;
}int score=scoreOption(option,normalizedTask,masterId);
if(isUnlocked(option)){if(selected==null||score>selectedScore){selected=option;
selectedScore=score;
}}else if(lockedUpgrade==null||score>lockedScore){lockedUpgrade=option;
lockedScore=score;
}}if(selected==null){return lockedRecommendation(assignment,lockedUpgrade);
}TaskStrategy strategy=strategyFor(normalizedTask,selected.location,false);
return new Recommendation(selected.location,strategy.getMethod(),buildReason(selected,normalizedTask,selectedScore,masterId)+" "+strategy.getRationale(),selected.travel,formatCannon(selected.cannonSupport),formatRequirements(selected,lockedUpgrade),text(852),RouteCatalog.find(normalizedTask,selected.location),strategy);
}private Recommendation turaelBoostRecommendation(String assignment){TuraelBoost.Entry entry=TuraelBoost.find(assignment);
if(entry==null){return null;
}TaskStrategy strategy=strategyFor(assignment,entry.getLocation(),false).withAdditionalTags(TaskStrategy.MethodTag.TURAEL_POINT_BOOST);
return new Recommendation(entry.getLocation(),strategy.getMethod(),text(853)+text(854)+text(855)+"supports it. "+strategy.getRationale(),entry.getTravel(),entry.getCannon(),entry.getRequirements(),text(856),RouteCatalog.find(assignment,entry.getLocation()),strategy);
}private Recommendation assignedAreaRecommendation(String normalizedTask,String assignedLocation,int masterId){String area=isAssignedArea(assignedLocation)?assignedLocation.trim():"Assigned Slayer area";
if(masterId!=KRYSTILIA&&isWilderness(area)){return new Recommendation(text(857),text(858),text(859),text(860),"Not recommended",text(861),text(862));
}TaskStrategy strategy=strategyFor(normalizedTask,area,masterId==KRYSTILIA);
return new Recommendation(area,strategy.getMethod(),(masterId==KONAR_MASTER_ID?text(863)+text(864):text(865)+text(864))+" "+strategy.getRationale(),travelForArea(area),formatCannon(cannonForArea(area)),text(866),masterId==KONAR_MASTER_ID?text(867):"Assigned area required",RouteCatalog.find(normalizedTask,area),strategy);
}private Recommendation wildernessRecommendation(String assignment){String normalized=normalize(assignment);
String location;
if(normalized.equals(text(514))||normalized.equals("ankou")||normalized.equals("black demons")||normalized.equals("dust devils")||normalized.equals("greater demons")||normalized.equals("hellhounds")){location=text(868);
}else if(normalized.equals("bloodveld")||normalized.equals(text(483))){location=text(869);
}else{location=text(870);
}TaskStrategy strategy=strategyFor(assignment,location,true);
return new Recommendation(location,strategy.getMethod(),text(871)+text(872)+strategy.getRationale(),text(873),formatCannon(CannonSupport.OPTIONAL),text(874),text(875),RouteCatalog.find(location),strategy);
}private Recommendation genericRecommendation(String assignment,int masterId){SlayerTaskTravelAuditCatalog.Entry auditedTravel=SlayerTaskTravelAuditCatalog.find(assignment);
if(auditedTravel!=null){TaskStrategy auditedStrategy=strategyFor(assignment,auditedTravel.getLocation(),masterId==KRYSTILIA);
return new Recommendation(auditedTravel.getLocation(),auditedStrategy.getMethod(),text(876)+auditedStrategy.getRationale(),auditedTravel.getTravel(),auditedTravel.getCannon(),text(877),masterId==KRYSTILIA?text(878):text(852),RouteCatalog.find(assignment,auditedTravel.getLocation()),auditedStrategy);
}TaskStrategy strategy=strategyFor(assignment,"Standard Slayer location",masterId==KRYSTILIA);
return new Recommendation("Standard Slayer location",strategy.getMethod(),(strategy.isReviewed()?text(879)+text(880):text(881))+strategy.getRationale(),text(882),"Check location rules",text(883),masterId==KRYSTILIA?text(878):text(884),null,strategy);
}private Recommendation lockedRecommendation(String assignment,LocationOption lockedOption){if(lockedOption==null){return genericRecommendation(assignment,0);
}TaskStrategy strategy=strategyFor(assignment,lockedOption.location,false);
return new Recommendation("Location locked",strategy.getMethod(),text(885)+strategy.getRationale(),lockedOption.travel,formatCannon(lockedOption.cannonSupport),requirementName(lockedOption)+" required",text(884),null,strategy);
}private boolean isUnlocked(LocationOption option){return(option.quest==null||option.quest.getState(client)==QuestState.FINISHED)&&(option.skill==null||client.getRealSkillLevel(option.skill)>=option.skillLevel);
}private String formatRequirements(LocationOption selected,LocationOption lockedUpgrade){String selectedRequirement;
if(selected.skill!=null){selectedRequirement=selected.skillLevel+" "+selected.skill.getName()+" — met";
}else{selectedRequirement=selected.quest==null?"None":selected.questName+" — completed";
}if(lockedUpgrade==null||lockedUpgrade==selected){return selectedRequirement;
}return selectedRequirement+"; "+requirementName(lockedUpgrade)+" unlocks "+lockedUpgrade.location;
}private static String requirementName(LocationOption option){if(option==null){return "Location requirement";
}if(option.skill!=null){return option.skillLevel+" "+option.skill.getName();
}return option.questName==null||option.questName.trim().isEmpty()?"Location requirement":option.questName;
}private int scoreOption(LocationOption option,String normalizedTask,int masterId){int speed=speedRating(option);
int profit=profitRating(option);
int afk=afkRating(option);
int score;
switch(playstyle()){case PROFIT:score=profit*4+speed+afk/4;
break;
case FAST_XP:default:score=speed*5;
break;
}boolean cannonAvailable=option.cannonSupport==CannonSupport.RECOMMENDED||option.cannonSupport==CannonSupport.OPTIONAL;
boolean cannonUnlocked=Quest.DWARF_CANNON.getState(client)==QuestState.FINISHED;
switch(cannonPreference()){case PREFER:if(cannonAvailable&&cannonUnlocked){score+=option.cannonSupport==CannonSupport.RECOMMENDED?70:38;
}else{score-=18;
}break;
case NEVER:if(option.cannonSupport==CannonSupport.RECOMMENDED){score-=130;
}else if(option.cannonSupport==CannonSupport.OPTIONAL){score+=6;
}else{score+=18;
}break;
case ALLOW:default:if(cannonAvailable&&cannonUnlocked){score+=12;
}break;
}boolean burstAvailable=supportsBurst(option);
switch(burstPreference()){case PREFER:score+=burstAvailable?72:-16;
break;
case NEVER:score+=burstAvailable?-130:18;
break;
case ALLOW:default:if(burstAvailable){score+=12;
}break;
}score+=travelScore(option.travel);
score+=shardPreferenceBonusForTest(shardPreference(),normalizedTask,option.location);
return score;
}private int speedRating(LocationOption option){String text=normalize(option.location+" "+option.method);
int rating=42;
if(text.contains("burst")||text.contains("barrage")){rating+=42;
}if(text.contains("cannon")){rating+=32;
}if(text.contains("multi combat")||text.contains("clustered")||text.contains("stacked")){rating+=14;
}if(text.contains("single combat")){rating-=14;
}return clampRating(rating);
}private int profitRating(LocationOption option){String text=normalize(option.location+" "+option.method);
int rating=34;
if(text.contains("higher value")||text.contains(text(886))){rating+=48;
}if(text.contains(text(485))||text.contains("kraken")||text.contains("gargoyle")||text.contains("skeletal wyvern")){rating+=35;
}if(text.contains("darkmeyer")||text.contains("cave horror")||text.contains("abyssal")){rating+=24;
}if(text.contains("ancient shard")||text.contains("totem")){rating+=18;
}return clampRating(rating);
}private int afkRating(LocationOption option){String text=normalize(option.method);
int rating=45;
if(text.contains("single combat")||text.contains("melee")){rating+=24;
}if(text.contains("ranged")){rating+=12;
}if(text.contains("cannon")){rating+=12;
}if(text.contains("burst")||text.contains("barrage")||text.contains("stacked")){rating-=26;
}if(text.contains("finish each kill")||text.contains("witchwood")||text.contains(text(421))){rating-=18;
}return clampRating(rating);
}private int travelScore(String route){String normalized=normalize(route);
boolean directTeleport=normalized.contains("teleport")||normalized.contains("slayer ring")||normalized.contains("xeric")||normalized.contains("rada")||normalized.contains("drakan")||normalized.contains("digsite pendant")||normalized.contains("fairy ring");
boolean freeOrReusable=normalized.contains(text(887))||normalized.contains("fairy ring")||normalized.contains("spirit tree")||normalized.contains("run from")||normalized.contains("then run");
boolean likelyConsumable=normalized.contains("games necklace")||normalized.contains("talisman")||normalized.contains("slayer ring")||normalized.contains("digsite pendant")||normalized.contains("teleport crystal")||normalized.contains("house teleport");
switch(travelPreference()){case CHEAPEST:if(freeOrReusable){return 52;
}return likelyConsumable?-20:18;
case AVOID_CONSUMABLES:return likelyConsumable?-70:42;
case FASTEST:default:return directTeleport?45:8;
}}private String buildReason(LocationOption option,String normalizedTask,int score,int masterId){StringBuilder reason=new StringBuilder();
reason.append(playstyle()).append(text(888));
switch(playstyle()){case PROFIT:reason.append(text(889));
break;
case FAST_XP:default:reason.append(text(890));
break;
}if(cannonPreference()==Preference.Cannon.PREFER&&option.cannonSupport!=CannonSupport.NOT_ALLOWED){reason.append(text(891));
}else if(cannonPreference()==Preference.Cannon.NEVER&&option.cannonSupport==CannonSupport.NOT_ALLOWED){reason.append(text(892));
}if(burstPreference()==Preference.Burst.PREFER&&supportsBurst(option)){reason.append(text(893));
}else if(burstPreference()==Preference.Burst.NEVER&&!supportsBurst(option)){reason.append(text(894));
}if(shardPreferenceBonusForTest(shardPreference(),normalizedTask,option.location)>0){reason.append(text(895));
}reason.append(text(896)).append(travelPreference().toString().toLowerCase(Locale.ENGLISH)).append(". Score: ").append(score).append('.');
return reason.toString();
}private static boolean supportsBurst(LocationOption option){String method=normalize(option.method);
return method.contains("burst")||method.contains("barrage");
}private static int clampRating(int value){return Math.max(0,Math.min(100,value));
}private Preference.Playstyle playstyle(){return config==null||config.playstyle()==null?Preference.Playstyle.FAST_XP:config.playstyle();
}private Preference.CombatStyle combatStylePreference(){return config==null||config.combatStylePreference()==null?Preference.CombatStyle.AUTOMATIC:config.combatStylePreference();
}private Preference.Cannon cannonPreference(){return config==null||config.cannonPreference()==null?Preference.Cannon.ALLOW:config.cannonPreference();
}private Preference.Burst burstPreference(){return config==null||config.burstPreference()==null?Preference.Burst.ALLOW:config.burstPreference();
}private Preference.Travel travelPreference(){return config==null||config.travelPreference()==null?Preference.Travel.FASTEST:config.travelPreference();
}private Preference.Shard shardPreference(){return config==null||config.shardPreference()==null?Preference.Shard.NO_PREFERENCE:config.shardPreference();
}static int shardPreferenceBonusForTest(Preference.Shard preference,String assignment,String location){if(preference==null||preference==Preference.Shard.NO_PREFERENCE){return 0;
}String task=normalize(assignment);
String area=normalize(location);
boolean ancientShardArea=!task.equals("ghost")&&!task.equals("ghosts")&&(area.contains(text(150))||area.contains("giants den"));
boolean crystalShardArea=area.contains(text(897));
switch(preference){case ANCIENT_SHARD:return ancientShardArea?1000:0;
case CRYSTAL_SHARD:return crystalShardArea?1000:0;
case ANCIENT_AND_CRYSTAL_SHARD:return ancientShardArea||crystalShardArea?1000:0;
case NO_PREFERENCE:default:return 0;
}}private String formatCannon(CannonSupport support){if(support==CannonSupport.NOT_ALLOWED){return "Not allowed";
}if(support==CannonSupport.UNKNOWN){return cannonPreference()==Preference.Cannon.NEVER?"Disabled by preference":text(898);
}if(cannonPreference()==Preference.Cannon.NEVER){return "Disabled by preference";
}if(Quest.DWARF_CANNON.getState(client)!=QuestState.FINISHED){return text(899);
}if(cannonPreference()==Preference.Cannon.PREFER){return support==CannonSupport.RECOMMENDED?"Preferred and recommended":"Preferred where practical";
}return support==CannonSupport.RECOMMENDED?"Recommended":"Optional";
}private TaskStrategy strategyFor(String assignment,String location,boolean wilderness){return SlayerTaskStrategyCatalog.resolve(assignment,playstyle(),cannonPreference(),burstPreference(),combatStylePreference(),location,wilderness);
}private static String travelForArea(String area){String normalized=normalize(area);
if(normalized.contains(text(150))){return text(900);
}if(normalized.contains("slayer tower")){return text(901);
}if(normalized.contains(text(902))){return text(903);
}if(normalized.contains(text(904))){return text(905);
}if(normalized.contains(text(390))){return text(906);
}if(normalized.contains("lighthouse")){return text(907);
}if(normalized.contains(text(908))){return "Lunar Isle teleport";
}if(normalized.contains(text(504))){return text(909);
}if(normalized.contains("mos le harmless")){return text(910);
}if(normalized.contains(text(911))){return text(912);
}if(normalized.contains("god wars")){return text(913);
}if(normalized.contains(text(914))){return text(915);
}if(normalized.contains(text(916))){return text(917);
}return text(918);
}private static CannonSupport cannonForArea(String area){String normalized=normalize(area);
if(normalized.contains("catacombs")||normalized.contains("slayer tower")||normalized.contains(text(902))||normalized.contains(text(390))||normalized.contains("kraken")||normalized.contains("god wars")||normalized.contains("mos le harmless")){return CannonSupport.NOT_ALLOWED;
}if(normalized.contains("lighthouse")||normalized.contains(text(504))||normalized.contains(text(904))||normalized.contains(text(897))||normalized.contains(text(908))||normalized.contains(text(919))||normalized.contains("death plateau")||normalized.contains(text(920))){return CannonSupport.RECOMMENDED;
}return CannonSupport.UNKNOWN;
}private static boolean isAssignedArea(String area){if(area==null){return false;
}String normalized=normalize(area);
return!normalized.isEmpty()&&!normalized.equals("not restricted")&&!normalized.equals("assigned area")&&!normalized.equals("unknown")&&!normalized.equals("-");
}private static boolean isWilderness(String value){String normalized=normalize(value);
return normalized.contains("wilderness")||normalized.contains(text(549))||normalized.contains("forinthry");
}private static Map<String,List<LocationOption>>createTaskLocations(){Map<String,List<LocationOption>>groups=new LinkedHashMap<>();
for(String[]fields:ResourceTable.decodedRows(text(921),9)){if(!fields[0].equals("O")){throw new IllegalStateException(text(922)+fields[0]);
}String aliasKey=fields[1];
String requirementType=fields[6];
Quest quest=requirementType.equals("QUEST")?Quest.valueOf(fields[7]):null;
Skill skill=requirementType.equals("SKILL")?Skill.valueOf(fields[7]):null;
int skillLevel=skill==null||fields[8].isEmpty()?0:Integer.parseInt(fields[8]);
groups.computeIfAbsent(aliasKey,unused->new ArrayList<>()).add(new LocationOption(fields[2],fields[3],fields[4],CannonSupport.valueOf(fields[5]),quest,quest==null?"":fields[8],skill,skillLevel,false));
}Map<String,List<LocationOption>>result=new HashMap<>();
for(Map.Entry<String,List<LocationOption>>group:groups.entrySet()){List<LocationOption>options=Collections.unmodifiableList(new ArrayList<>(group.getValue()));
for(String alias:group.getKey().split("\\|",-1)){if(result.put(normalize(alias),options)!=null){throw new IllegalStateException(text(923)+alias);
}}}if(result.isEmpty()){throw new IllegalStateException(text(924));
}return Collections.unmodifiableMap(result);
}private static String normalize(String value){if(value==null){return "";
}return value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim();
}private enum CannonSupport{RECOMMENDED,OPTIONAL,NOT_ALLOWED,UNKNOWN}private static final class LocationOption{private final String location;
private final String method;
private final String travel;
private final CannonSupport cannonSupport;
private final Quest quest;
private final String questName;
private final Skill skill;
private final int skillLevel;
private final boolean wilderness;
private LocationOption(String location,String method,String travel,CannonSupport cannonSupport,Quest quest,String questName,Skill skill,int skillLevel,boolean wilderness){this.location=location;
this.method=method;
this.travel=travel;
this.cannonSupport=cannonSupport;
this.quest=quest;
this.questName=questName;
this.skill=skill;
this.skillLevel=Math.max(0,skillLevel);
this.wilderness=wilderness;
}}}
