package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
class SlayerRegularInventoryAuditCatalog{private static final Policy DIRECT=new Policy(2,6,12,true);
private static final Policy SAFESPOT=new Policy(0,0,24,true);
private static final Policy PRAYER=new Policy(5,0,16,true);
private static final Map<String,Policy>POLICIES=createPolicies();
private SlayerRegularInventoryAuditCatalog(){}static void apply(String assignment,MethodRules.Builder rules,TaskStrategy strategy){String task=normalize(assignment);
Policy policy=POLICIES.get(task);
if(policy!=null){policy.apply(rules,strategy);
applyTaskSpecificSupplies(task,rules,strategy);
return;
}MethodRules.DamageControl control=strategy==null?MethodRules.DamageControl.DIRECT_DAMAGE:strategy.getDamageProfile()==TaskStrategy.DamageProfile.ZERO_WHILE_PROTECTED?MethodRules.DamageControl.PRAYER_PROTECTED:strategy.getDamageProfile()==TaskStrategy.DamageProfile.ZERO_WHILE_SAFESPOTTING?MethodRules.DamageControl.SAFESPOT:MethodRules.DamageControl.DIRECT_DAMAGE;
(control==MethodRules.DamageControl.SAFESPOT?SAFESPOT:control==MethodRules.DamageControl.PRAYER_PROTECTED?PRAYER:DIRECT).apply(rules,strategy);
}static int sizeForTest(){return POLICIES.size();
}private static void applyTaskSpecificSupplies(String task,MethodRules.Builder rules,TaskStrategy strategy){if(task.equals("bandits")||task.equals("crocodiles")||task.equals("lizards")){rules.require(text(413),1,MethodRules.InventoryGroup.PROTECTION,text(414),text(415),text(416),text(417),text(418),text(419));
}if(task.equals(text(925))){rules.restore("prayer potion","super restore").restoreSlots(3).food(6).loot(10).require("Poison protection",1,MethodRules.InventoryGroup.PROTECTION,text(486),text(488),"antipoison").require("Nature runes",200,MethodRules.InventoryGroup.RUNES,"nature rune");
}if(task.equals("spiritual creatures")){rules.require(PotionPolicy.EXTENDED_STAMINA_DISPLAY,1,MethodRules.InventoryGroup.UTILITY,PotionPolicy.staminaAlternatives());
}if(task.equals("greater demons")){rules.require("Ash sanctifier",1,MethodRules.InventoryGroup.UTILITY,"ash sanctifier");
}if(task.equals("basilisks")){boolean ranged=strategy!=null&&strategy.getStyle()==TaskStrategy.CombatStyle.RANGED;
rules.restore("prayer potion","super restore").restoreSlots(6).food(ranged?0:6).loot(ranged?16:9).spell(MethodRules.Spellbook.STANDARD,text(926)).runePouch(true).pouchRune(net.runelite.api.gameval.ItemID.AIRRUNE,"Air",500).pouchRune(net.runelite.api.gameval.ItemID.LAWRUNE,"Law",200).pouchRune(net.runelite.api.gameval.ItemID.NATURERUNE,"Nature",200);
}if(task.equals("aquanites")){rules.restore("prayer potion","super restore").restoreSlots(5).food(4).loot(10).spell(MethodRules.Spellbook.STANDARD,text(506)).runePouch(true).pouchRune(net.runelite.api.gameval.ItemID.FIRERUNE,"Fire",1000).pouchRune(net.runelite.api.gameval.ItemID.NATURERUNE,"Nature",250).require(text(927),1,MethodRules.InventoryGroup.SWITCH,text(928),"dragon claws","voidwaker",text(929),text(930),text(931),text(932)).require("Seed box",1,MethodRules.InventoryGroup.UTILITY,"seed box");
}if(task.equals("skeletal wyvern")||task.equals(text(264))){TaskStrategy.CombatStyle style=strategy==null?TaskStrategy.CombatStyle.MELEE:strategy.getStyle();
boolean safespot=style==TaskStrategy.CombatStyle.RANGED||style==TaskStrategy.CombatStyle.MAGIC;
rules.restore("prayer potion","super restore").restoreSlots(safespot?2:4).food(safespot?6:8).loot(safespot?16:11);
if(style==TaskStrategy.CombatStyle.MELEE){rules.require("Special attack weapon",1,MethodRules.InventoryGroup.SWITCH,"voidwaker","dragon claws","burning claws",text(933),text(934),"dragon dagger p","dragon dagger");
}if(style!=TaskStrategy.CombatStyle.MAGIC){rules.spell(MethodRules.Spellbook.STANDARD,text(506)).runePouch(true).pouchRune(net.runelite.api.gameval.ItemID.FIRERUNE,"Fire",1000).pouchRune(net.runelite.api.gameval.ItemID.NATURERUNE,"Nature",250);
}}if(task.equals("kalphite")||task.equals("kalphites")){rules.restore("prayer potion","super restore").restoreSlots(5).food(0).loot(9).require("Poison protection",1,MethodRules.InventoryGroup.PROTECTION,text(486),"sanfew serum",text(488),"antipoison").require("Special attack weapon",1,MethodRules.InventoryGroup.SWITCH,text(933),text(934),"dragon dagger p","dragon dagger");
}}private static Map<String,Policy>createPolicies(){Map<String,Policy>map=new LinkedHashMap<>();
for(String[]row:ResourceTable.rows(text(935),5)){put(map,new Policy(Integer.parseInt(row[1]),Integer.parseInt(row[2]),Integer.parseInt(row[3]),Boolean.parseBoolean(row[4])),row[0]);
}return Collections.unmodifiableMap(map);
}private static void put(Map<String,Policy>map,Policy policy,String...taskNames){for(String assignment:taskNames){String key=normalize(assignment);
if(map.put(key,policy)!=null){throw new IllegalStateException(text(936)+assignment);
}}}private static String normalize(String value){return value==null?"":value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim().replaceFirst("^the\\s+","");
}private static final class Policy{private final int restoreSlots;
private final int food;
private final int loot;
private final boolean styleBoost;
private Policy(int restoreSlots,int food,int loot,boolean styleBoost){this.restoreSlots=restoreSlots;
this.food=food;
this.loot=loot;
this.styleBoost=styleBoost;
}private void apply(MethodRules.Builder rules,TaskStrategy strategy){boolean preventsExpectedDamage=strategy!=null&&(strategy.getDamageProfile()==TaskStrategy.DamageProfile.ZERO_WHILE_PROTECTED||strategy.getDamageProfile()==TaskStrategy.DamageProfile.ZERO_WHILE_SAFESPOTTING);
rules.restore("prayer potion","super restore").restoreSlots(restoreSlots).food(preventsExpectedDamage?0:food).loot(loot).includeStyleBoost(styleBoost);
}}}
