package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
class SlayerElementalWeaknessCatalog{private enum Element{AIR("Wind"),EARTH("Earth"),FIRE("Fire"),WATER("Water");
private final String spellLabel;
Element(String spellLabel){this.spellLabel=spellLabel;
}}static final class Entry{private final Element element;
private final int percent;
private Entry(Element element,int percent){this.element=element;
this.percent=percent;
}String getSpellLabel(){return element.spellLabel;
}int getPercent(){return percent;
}}private static final Map<String,Entry>ENTRIES=createEntries();
private SlayerElementalWeaknessCatalog(){}static Entry find(String assignment){return ENTRIES.get(normalize(assignment));
}static TaskStrategy preferenceStrategy(String assignment,boolean wilderness){Entry entry=find(assignment);
if(entry==null){return null;
}TaskStrategy.Builder builder=TaskStrategy.builder(TaskStrategy.CombatStyle.MAGIC,"Use the best "+entry.element.spellLabel+text(240)+entry.percent+"% "+entry.element.spellLabel+" weakness").armourFocus(TaskStrategy.ArmourFocus.DAMAGE).costPolicy(wilderness?TaskStrategy.CostPolicy.LOW_RISK:TaskStrategy.CostPolicy.EFFICIENT).weapons(staffPriorities(entry.element)).runePouch(true).strictWeaponProfile(true).prayers(3).tags(TaskStrategy.MethodTag.PREFERENCE_ONLY_ALTERNATIVE).reviewed(TaskResearch.REVIEW_DATE);
if(wilderness){builder.tags(TaskStrategy.MethodTag.PREFERENCE_ONLY_ALTERNATIVE,TaskStrategy.MethodTag.WILDERNESS);
}return builder.build();
}static int sizeForTest(){return ENTRIES.size();
}private static String[]staffPriorities(Element element){switch(element){case WATER:return new String[]{text(241),"kodai wand","mist battlestaff","water battlestaff",text(242),"staff of water"};
case FIRE:return new String[]{text(243),text(241),text(244),text(245),"fire battlestaff",text(246),"staff of fire"};
case EARTH:return new String[]{text(241),text(247),text(248),"earth battlestaff",text(249),"staff of earth"};
case AIR:default:return new String[]{text(243),text(241),text(244),"air battlestaff",text(250),"staff of air"};
}}private static Map<String,Entry>createEntries(){Map<String,Entry>map=new LinkedHashMap<>();
for(String[]row:ResourceTable.rows(text(251),3)){put(map,Element.valueOf(row[1]),Integer.parseInt(row[2]),row[0]);
}return Collections.unmodifiableMap(map);
}private static void put(Map<String,Entry>map,Element element,int percent,String...taskNames){for(String assignment:taskNames){String key=normalize(assignment);
if(map.put(key,new Entry(element,percent))!=null){throw new IllegalStateException(text(252)+assignment);
}}}private static String normalize(String value){return value==null?"":value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim().replaceFirst("^the\\s+","");
}}
