package com.slayerplus;
import java.util.*;
public final class SlayerRoutePlanCatalog{private static final Map<RouteKey,RoutePlan>PLANS=SlayerRoutePlanResource.load();
private static final Set<RouteKey>KEYS=Collections.unmodifiableSet(new LinkedHashSet<>(PLANS.keySet()));
private static final Collection<RoutePlan>UNIQUE_PLANS=Collections.unmodifiableSet(new LinkedHashSet<>(PLANS.values()));
private SlayerRoutePlanCatalog(){}public static RoutePlan resolve(String assignment,String location,boolean boss){return PLANS.get(RouteKey.of(assignment,location,boss));
}public static boolean hasExactPlan(String assignment,String location,boolean boss){return resolve(assignment,location,boss)!=null;
}public static Collection<RoutePlan>allPlans(){return UNIQUE_PLANS;
}public static final class RouteKey{private final String assignment;
private final String location;
private final boolean boss;
private RouteKey(String assignment,String location,boolean boss){this.assignment=RouteEvidence.normalize(assignment);
this.location=RouteEvidence.normalize(location);
this.boss=boss;
}public static RouteKey of(String assignment,String location,boolean boss){return new RouteKey(assignment,location,boss);
}public String getTaskName(){return assignment;
}public String getLocation(){return location;
}public boolean isBoss(){return boss;
}@Override public boolean equals(Object other){if(this==other){return true;
}if(!(other instanceof RouteKey)){return false;
}RouteKey that=(RouteKey)other;
return boss==that.boss&&assignment.equals(that.assignment)&&location.equals(that.location);
}@Override public int hashCode(){return Objects.hash(assignment,location,boss);
}@Override public String toString(){return assignment+"|"+location+"|"+boss;
}}public static boolean hasExplicitPlanForTest(String assignment,String location,boolean boss){return hasExactPlan(assignment,location,boss);
}public static Set<RouteKey>keysForTest(){return KEYS;
}public static Collection<RoutePlan>plansForTest(){return UNIQUE_PLANS;
}}
