package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
public final class SlayerTeleportRouteRegistry{private SlayerTeleportRouteRegistry(){}public static String menuDestination(String itemName,String routeDestination){String family=normalize(itemName);
String destination=normalize(routeDestination);
if(family.contains("slayer ring")&&(destination.equals("dark beasts")||destination.equals("me2 caves"))){return text(1006);
}if(family.contains("slayer ring")&&isWyrmscraigCavernDestination(destination)){return text(37);
}if((family.contains(text(686))||family.contains(text(687)))&&isMorUlRekDestination(destination)){return text(634);
}if(family.contains(text(31))&&isDuradelDestination(destination)){return "Slayer Master";
}if(family.contains("karamja gloves")&&isShiloMineDestination(destination)){return "Gem Mine";
}if(family.contains(text(35))&&isKonarDestination(destination)){return text(36);
}if(isAchievementDiaryCape(family)){String diaryRegion=achievementDiaryRegion(destination);
if(diaryRegion!=null){return diaryRegion;
}}if((family.contains("max cape")||family.contains("construction cape")||family.contains("construct cape"))&&isHouseDestination(destination)){return text(675);
}return clean(routeDestination);
}public static Set<String>destinationAliases(String itemName,String routeDestination){Set<String>aliases=new LinkedHashSet<>();
add(aliases,routeDestination);
add(aliases,menuDestination(itemName,routeDestination));
String family=normalize(itemName);
String destination=normalize(routeDestination);
if(family.contains("slayer ring")){addSlayerRingAliases(aliases,destination);
}if((family.contains(text(686))||family.contains(text(687)))&&isMorUlRekDestination(destination)){add(aliases,text(634));
add(aliases,text(1007));
add(aliases,text(1008));
}if(family.contains(text(31))&&isDuradelDestination(destination)){add(aliases,"Slayer Master");
add(aliases,"Duradel");
add(aliases,"Kuradal");
}if(family.contains("karamja gloves")&&isShiloMineDestination(destination)){add(aliases,"Gem Mine");
add(aliases,text(1009));
}if(family.contains(text(35))&&isKonarDestination(destination)){add(aliases,text(36));
add(aliases,"Konar");
}if(isAchievementDiaryCape(family)){add(aliases,achievementDiaryRegion(destination));
}if((family.contains("max cape")||family.contains("construction cape")||family.contains("construct cape"))&&isHouseDestination(destination)){add(aliases,"POH");
add(aliases,"House");
add(aliases,"Home");
add(aliases,"Player-owned house");
add(aliases,text(1010));
add(aliases,"Tele to house");
add(aliases,text(675));
add(aliases,text(1011));
}if((family.contains("max cape")||family.contains("construction cape")||family.contains("construct cape"))&&isPohPortalDestination(destination)){add(aliases,pohPortalLeaf(routeDestination));
}return aliases;
}private static boolean isAchievementDiaryCape(String family){return family.contains("achievement diary cape")||family.contains("achievement cape");
}private static String achievementDiaryRegion(String destination){String taskmaster=normalize(destination).replaceFirst("^(?:achievement diary cape|achievement cape)\\s+","").replaceFirst("^\\d+\\s+","").trim();
switch(taskmaster){case "two pints":return "Ardougne";
case "jarr":return "Desert";
case "sir rebral":return "Falador";
case "thorodin":return "Fremennik";
case "the wedge":case "wedge":return "Kandarin";
case "pirate jackie the fruit":case "pirate jackie":return "Karamja";
case "elise":return text(1012);
case "hatius cosaintus":case "hatius":return text(1013);
case "le sabre":case "le sabr":case "le sabre taskmaster":return "Morytania";
case "toby":return "Varrock";
case "lesser fanatic":return "Wilderness";
case "elder gnome child":return "Western Provinces";
case "twiggy o korn":case "twiggy":return text(1014);
default:return null;
}}public static boolean matchesEasyTeleportsConfigKey(String itemName,String routeDestination,String configKey){String key=normalizeConfigKey(configKey);
if(key.isEmpty()){return false;
}Set<String>aliases=destinationAliases(itemName,routeDestination);
for(String alias:aliases){String normalizedAlias=normalize(alias);
if(normalizedAlias.isEmpty()){continue;
}if(key.equals(normalizedAlias)){return true;
}Set<String>aliasTokens=tokens(normalizedAlias);
Set<String>keyTokens=tokens(key);
if(aliasTokens.isEmpty()||keyTokens.isEmpty()){continue;
}Set<String>meaningfulAliasTokens=meaningfulTokens(aliasTokens);
if(!meaningfulAliasTokens.isEmpty()&&keyTokens.containsAll(meaningfulAliasTokens)){return true;
}Set<String>meaningfulKeyTokens=meaningfulTokens(keyTokens);
if(meaningfulKeyTokens.size()>=2&&aliasTokens.containsAll(meaningfulKeyTokens)){return true;
}}return false;
}private static void addSlayerRingAliases(Set<String>aliases,String destination){if(destination.equals("dark beasts")||destination.equals("me2 caves")){add(aliases,"Dark Beasts");
add(aliases,text(1006));
return;
}if(destination.equals(text(904))||destination.equals(text(1015))||destination.equals("slayer stronghold")){add(aliases,text(142));
add(aliases,text(1016));
add(aliases,text(1017));
return;
}if(destination.equals(text(1018))||destination.equals("slayer tower")){add(aliases,text(1019));
add(aliases,"Slayer Tower");
return;
}if(destination.equals(text(1020))||destination.equals(text(1021))){add(aliases,text(1022));
add(aliases,text(1023));
return;
}if(destination.equals(text(1024))||destination.equals("haunted mine")){add(aliases,"Tarn's Lair");
add(aliases,"Haunted Mine");
return;
}if(isWyrmscraigCavernDestination(destination)){add(aliases,text(37));
add(aliases,text(1025));
add(aliases,"Mortimer");
}}private static boolean isWyrmscraigCavernDestination(String destination){return destination.equals(text(1026))||destination.equals(text(1027))||destination.equals("mortimer");
}private static boolean isMorUlRekDestination(String destination){return destination.equals("mor ul rek")||destination.equals("morulrek")||destination.equals(text(1028))||destination.equals("inner city");
}private static boolean isDuradelDestination(String destination){return destination.equals("duradel")||destination.equals("kuradal")||destination.equals("slayer master");
}private static boolean isShiloMineDestination(String destination){return destination.equals("gem mine")||destination.equals(text(1029))||destination.equals(text(1030));
}private static boolean isKonarDestination(String destination){return destination.equals("konar")||destination.equals(text(1031))||destination.equals(text(390));
}private static boolean isHouseDestination(String destination){return destination.equals("poh")||destination.equals("house")||destination.equals("home")||destination.equals("player owned house")||destination.equals("tele to house")||destination.equals(text(1032))||destination.startsWith("tele to house ")||destination.startsWith(text(1033))||destination.equals(text(393))||destination.equals(text(1034))||destination.startsWith(text(1035))||destination.startsWith(text(1036));
}private static boolean isPohPortalDestination(String destination){return destination.startsWith("poh portal ")||destination.startsWith("poh portals ");
}private static String pohPortalLeaf(String routeDestination){String destination=clean(routeDestination);
String leaf=destination.replaceFirst("(?i)^POH\\s+Portals?\\s*:?\\s*","");
return leaf.equals(destination)?"":leaf;
}private static Set<String>meaningfulTokens(Set<String>values){Set<String>result=new HashSet<>();
for(String token:values){if(token.length()<3||GENERIC_CONFIG_TOKENS.contains(token)){continue;
}result.add(token);
}return result;
}private static Set<String>tokens(String value){String normalized=normalize(value);
if(normalized.isEmpty()){return new HashSet<>();
}return new HashSet<>(Arrays.asList(normalized.split("\\s+")));
}private static final Set<String>GENERIC_CONFIG_TOKENS=new HashSet<>(Arrays.asList("replacement","teleport","teleports","ring","necklace","amulet","bracelet","cape","gloves","legs","blessing","pendant","talisman","games","skills","combat","wealth","glory","slayer","max","construction","construct","radas","rad","of","the","to"));
private static String normalizeConfigKey(String key){if(key==null){return "";
}String value=key.replaceFirst("^replacement","");
value=value.replaceAll(text(1037),"$1 $2");
return normalize(value);
}private static void add(Set<String>values,String value){String clean=clean(value);
if(!clean.isEmpty()){values.add(clean);
}}private static String clean(String value){if(value==null){return "";
}return value.replaceAll(text(1038)," ").replaceAll("\\s+"," ").trim();
}private static String normalize(String value){return clean(value).toLowerCase(Locale.ROOT).replaceAll(text(9)," ").replaceAll("\\s+"," ").trim();
}}
