package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
public final class TravelRoutes{public static final class Option{private final String family;
private final String destination;
private Option(String family,String destination){this.family=family==null?"":family.trim();
this.destination=destination==null?"":destination.trim();
}public String getItemFamily(){return family;
}public String getDestination(){return destination;
}}private static final CatalogData DATA=loadCatalog();
private static final Map<String,List<Option>>FALLBACKS=DATA.fallbacks;
private static final Map<String,String>LOCATION_ALIASES=DATA.aliases;
static{validateOrThrow();
}private TravelRoutes(){}public static List<Option>fallbacksFor(String location){String key=normalize(location);
String alias=LOCATION_ALIASES.get(key);
if(alias!=null){key=alias;
}List<Option>options=FALLBACKS.get(key);
return options==null?Collections.emptyList():options;
}public static int liveCandidatePreference(String family){String item=normalize(family);
if(item.isEmpty()){return Integer.MIN_VALUE;
}if(item.contains("max cape")){return 100_000;
}if(item.contains("construction cape")||item.contains("construct cape")){return 90_000;
}if(item.contains("eternal")){return 80_000;
}if(item.contains(text(393))||item.contains("house tablet")||item.endsWith(" tablet")||item.contains("teleport scroll")){return 10_000;
}return 50_000;
}public static int liveCandidatePreference(String location,String family){String candidate=normalize(family);
List<Option>reviewed=fallbacksFor(location);
for(int index=0;
index<reviewed.size();
index++){String expected=normalize(reviewed.get(index).getItemFamily());
if(!expected.isEmpty()&&(candidate.equals(expected)||candidate.contains(expected)||expected.contains(candidate))){return 2_000_000-index*200_000+liveCandidatePreference(family);
}}return liveCandidatePreference(family);
}public static boolean requiresExternalTeleportHandoff(String location,String family,String destination){String area=normalize(location);
String item=normalize(family);
String target=normalize(destination);
return area.equals(text(1044))&&item.contains("ghommal")&&(item.contains("hilt")||item.contains("avernic defender"))&&target.equals("mor ul rek");
}public static boolean allowsLiveCandidate(String location,String family,String destination){String area=normalize(location);
String item=normalize(family);
String target=normalize(destination);
if(area.equals(text(897))){return target.contains(text(1045))||item.contains(text(1045));
}if(area.equals("mourner tunnels")){return item.contains("slayer ring")&&(target.equals("dark beasts")||target.equals("me2 caves"));
}return true;
}public static boolean locksFirstResolvedTravelItem(String location){String area=normalize(location);
return area.equals(text(916))||area.equals(text(678))||area.equals(text(736));
}public static boolean locksAuthoredTravelItem(String location){String area=normalize(location);
return area.equals(text(678))||area.equals(text(736));
}public static void validateOrThrow(){for(Map.Entry<String,List<Option>>entry:FALLBACKS.entrySet()){if(entry.getKey()==null||entry.getKey().trim().isEmpty()){throw new IllegalStateException(text(1046));
}if(entry.getValue()==null||entry.getValue().isEmpty()){throw new IllegalStateException(text(1047)+entry.getKey());
}Set<String>seen=new LinkedHashSet<>();
for(Option option:entry.getValue()){if(option==null||option.family.isEmpty()||option.destination.isEmpty()){throw new IllegalStateException(text(1048)+entry.getKey());
}if(SlayerTravelItemPolicy.hasExplicitUnusableState(option.family)){throw new IllegalStateException(text(1049)+entry.getKey()+" -> "+option.family);
}String key=normalize(option.family)+"|"+normalize(option.destination);
if(!seen.add(key)){throw new IllegalStateException(text(1050)+entry.getKey()+" -> "+key);
}}}if(allowsLiveCandidate(text(141),text(1051),text(1016))){throw new IllegalStateException(text(1052));
}if(!allowsLiveCandidate(text(137),text(1051),text(1006))){throw new IllegalStateException(text(1053));
}if(!(liveCandidatePreference("Max cape")>liveCandidatePreference("Construct. cape")&&liveCandidatePreference("Construct. cape")>liveCandidatePreference(text(675)))){throw new IllegalStateException(text(1054)+" house tablet");
}if(!requiresExternalTeleportHandoff(text(1055),text(1056),text(634))||requiresExternalTeleportHandoff(text(144),text(388),text(1057))){throw new IllegalStateException(text(1058));
}List<Option>infernoBank=fallbacksFor(text(1055));
if(infernoBank.isEmpty()||!normalize(infernoBank.get(0).family).equals(text(1059))||!normalize(infernoBank.get(0).destination).equals("mor ul rek")){throw new IllegalStateException(text(1060)+text(1061));
}}private static CatalogData loadCatalog(){Map<String,List<Option>>fallbacks=new LinkedHashMap<>();
Map<String,String>aliases=new LinkedHashMap<>();
for(String[]fields:ResourceTable.decodedRows(text(1062),4)){if(fields[0].equals("A")){String from=normalize(fields[1]);
String to=normalize(fields[2]);
String previous=aliases.put(from,to);
if(from.isEmpty()||to.isEmpty()||(previous!=null&&!previous.equals(to))){throw new IllegalStateException(text(1063)+fields[1]);
}}else if(fields[0].equals("F")){String location=normalize(fields[1]);
fallbacks.computeIfAbsent(location,ignored->new ArrayList<>()).add(new Option(fields[2],fields[3]));
}else{throw new IllegalStateException(text(1064)+fields[0]);
}}Map<String,List<Option>>frozen=new LinkedHashMap<>();
for(Map.Entry<String,List<Option>>entry:fallbacks.entrySet()){frozen.put(entry.getKey(),Collections.unmodifiableList(entry.getValue()));
}return new CatalogData(Collections.unmodifiableMap(frozen),Collections.unmodifiableMap(aliases));
}private static final class CatalogData{private final Map<String,List<Option>>fallbacks;
private final Map<String,String>aliases;
private CatalogData(Map<String,List<Option>>fallbacks,Map<String,String>aliases){this.fallbacks=fallbacks;
this.aliases=aliases;
}}private static String normalize(String value){if(value==null){return "";
}return value.toLowerCase(Locale.ROOT).replaceAll(text(9)," ").trim();
}}
