package com.slayerplus;
import java.util.*;
import lombok.Getter;
@Getter public final class TravelChoice{public enum Status{UNRESOLVED,PROVISIONAL_ITEM,RESOLVED_ITEM,RESOLVED_NON_ITEM}public enum Source{NONE,AUTHORED_FALLBACK,SHORTEST_PATH}private final String routeIdentity;
private final long generation;
private final Status status;
private final Source source;
private final int itemId;
private final String itemName;
private final String destination;
private final Set<String>equivalents;
private TravelChoice(String routeIdentity,long generation,Status status,Source source,int itemId,String itemName,String destination,Set<String>equivalents){this.routeIdentity=routeIdentity==null?"":routeIdentity;
this.generation=generation;
this.status=status==null?Status.UNRESOLVED:status;
this.source=source==null?Source.NONE:source;
this.itemId=itemId;
this.itemName=itemName==null?"":itemName.trim();
this.destination=destination==null?"":destination.trim();
this.equivalents=immutableFamilies(equivalents);
}public static TravelChoice unresolved(String routeIdentity,long generation){return new TravelChoice(routeIdentity,generation,Status.UNRESOLVED,Source.NONE,-1,"","",Collections.emptySet());
}public static TravelChoice provisionalItem(String routeIdentity,long generation,int itemId,String itemName,String destination){return provisionalItem(routeIdentity,generation,itemId,itemName,destination,singleFamily(itemName));
}public static TravelChoice provisionalItem(String routeIdentity,long generation,int itemId,String itemName,String destination,Set<String>equivalents){return new TravelChoice(routeIdentity,generation,Status.PROVISIONAL_ITEM,Source.AUTHORED_FALLBACK,itemId,itemName,destination,equivalents);
}public static TravelChoice resolvedItem(String routeIdentity,long generation,int itemId,String itemName,String destination){return resolvedItem(routeIdentity,generation,itemId,itemName,destination,singleFamily(itemName));
}public static TravelChoice resolvedItem(String routeIdentity,long generation,int itemId,String itemName,String destination,Set<String>equivalents){return new TravelChoice(routeIdentity,generation,Status.RESOLVED_ITEM,Source.SHORTEST_PATH,itemId,itemName,destination,equivalents);
}public static TravelChoice resolvedNonItem(String routeIdentity,long generation,String family,String destination){return new TravelChoice(routeIdentity,generation,Status.RESOLVED_NON_ITEM,Source.SHORTEST_PATH,-1,family,destination,Collections.emptySet());
}public boolean belongsTo(String identity){return identity!=null&&!identity.isEmpty()&&routeIdentity.equals(identity);
}public boolean physical(){return itemId>0&&(status==Status.PROVISIONAL_ITEM||status==Status.RESOLVED_ITEM);
}public boolean isResolved(){return status==Status.RESOLVED_ITEM||status==Status.RESOLVED_NON_ITEM;
}public boolean isProvisional(){return status==Status.PROVISIONAL_ITEM;
}public String travelIdentity(){return generation+"|"+routeIdentity+"|"+status+"|"+itemId+"|"+itemName+"|"+destination+"|"+equivalents;
}public boolean isStructurallyValid(){if(routeIdentity.isEmpty()){return status==Status.UNRESOLVED&&itemId<=0;
}if(status==Status.PROVISIONAL_ITEM||status==Status.RESOLVED_ITEM){return itemId>0&&!itemName.isEmpty()&&!equivalents.isEmpty();
}if(status==Status.RESOLVED_NON_ITEM){return itemId<=0;
}return itemId<=0;
}private static Set<String>singleFamily(String value){if(value==null||value.trim().isEmpty()){return Collections.emptySet();
}Set<String>result=new LinkedHashSet<>();
result.add(value.trim());
return result;
}private static Set<String>immutableFamilies(Set<String>source){if(source==null||source.isEmpty()){return Collections.emptySet();
}Set<String>copy=new LinkedHashSet<>();
for(String value:source){if(value!=null&&!value.trim().isEmpty()){copy.add(value.trim());
}}return copy.isEmpty()?Collections.emptySet():Collections.unmodifiableSet(copy);
}}
