package com.slayerplus;
import static com.slayerplus.Text.text;
import java.util.*;
class TuraelBoost{static final class Entry{private final String location;
private final String travel;
private final String cannon;
private final String requirements;
private Entry(String location,String travel,String cannon,String requirements){this.location=location;
this.travel=travel;
this.cannon=cannon;
this.requirements=requirements;
}String getLocation(){return location;
}String getTravel(){return travel;
}String getCannon(){return cannon;
}String getRequirements(){return requirements;
}boolean supportsCannon(){String value=normalize(cannon);
return!value.equals("not allowed")&&!value.equals("not needed");
}}private static final Map<String,Entry>ENTRIES=loadEntries();
private TuraelBoost(){}static Entry find(String assignment){return ENTRIES.get(normalize(assignment));
}static boolean isBoostProfile(String assignment,String location){Entry entry=find(assignment);
return entry!=null&&normalize(entry.location).equals(normalize(location));
}static int sizeForTest(){return ENTRIES.size();
}private static Map<String,Entry>loadEntries(){Map<String,Entry>entries=new LinkedHashMap<>();
for(String[]fields:ResourceTable.rows(text(1065),5)){put(entries,fields[0],new Entry(fields[1],fields[2],fields[3],fields[4]));
}entries.put(normalize("Dwarf"),entries.get(normalize("Dwarves")));
entries.put(normalize("Wolf"),entries.get(normalize("Wolves")));
return Collections.unmodifiableMap(entries);
}private static void put(Map<String,Entry>entries,String task,Entry entry){entries.put(normalize(task),entry);
if(normalize(task).endsWith("s")){entries.put(normalize(task).replaceFirst("s$",""),entry);
}}private static String normalize(String value){return value==null?"":value.toLowerCase(Locale.ENGLISH).replace('\u2019','\'').replaceAll(text(9)," ").trim();
}}
